### ISSUE TITLE
__init() of objects can be explicitly called by users

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-spec#100]
Currently, the spec doesn't disallow explicitly calling the __init() method. However, during a meeting today, Sanjiva pointed out that such explicit calls to the __init() method does not reinitialize the object properly. For example,
```ballerina
import ballerina/io;

public function main() {
    Foo f = new("Pubudu");
    f.misc["a"] = "A";
    io:println(f);

    f.__init("Fernando");
    io:println(f);
}

type Foo object {
    public string name;
    public map<string> misc = {};

    function __init(string name) {
        self.name = name;
    }
};
```
The above program would give the following output:
```
{name:"Pubudu", misc:{"a":"A"}}
{name:"Fernando", misc:{"a":"A"}}
```
As it can be seen, the `misc` field does not get initialized to its default value.

**Comment by jclark** [comment]
I agree that's confusing. We can say that __init cannot be called explicitly, but only indirectly by new. This would imply that it should not affect subtyping.

**Comment by jclark** [comment]
But what if I want to provide a method that reinitializes the object?  I want to share code between that method and __init. But __init isn't allowed to call other methods (because that would allow access to uninitialized fields). Maybe we should allow __init to be called on self.

**Comment by hasithaa** [comment]
Following is the protocol for Object initialization. 

1. allocating storage for the object
2. initializing each field with its default value, if it has one
3. initializing the methods of the object using the type's method definitions
4. calling the object's __init method, if there is one 

So when we say re-initializing an object, what are the steps we need to consider? We can reuse the same storage, and We can call the __init method (let's say calling on self), But I am not sure, whether we can do step 2 and 3, explicitly. I think those have to be part of the object re-initialization.

**Comment by jclark** [comment]
For step 3 there is nothing to do, since the methods cannot be changed.

**Comment by jclark** [comment]
My major concern is that we are treating __init differently from other double underscore methods, and one of the main design goals in switching from constructors to __init methods was to make __init be just like a regular method.

**Comment by sanjiva** [comment]
I think the usecase James has in mind is:
- I write a random method resetThyself()
- in that method I can call self.__init() as a way for me to get the initialization behavior of __init()
- I do whatever else "reset" logic I want

In that usage, __init() is not playing the role of an initializer but just a function and is there just to save you from having to write the same logic in the reinitialializer. 

I think we don't need that .. and the extra complexity on subtyping too.

On the comment you made just before this: I don't think of `__init` as any other double underscore method because its really a special thing for objects only.

One option is to change the other `__*` to `_*`.

**Comment by jclark** [comment]
Treating __init differently from other methods is extra complexity. In particular, making it not callable adds extra complexity for subtyping.

Making __init callable on self only is the same from a subtyping perspective as making it not explicitly callable at all (in both cases that would mean that the __init method is not considered for subtyping).

**Comment by sanjiva** [comment]
Its extra complexity for us .. for users its just "I've got an object with me, is this compatible with that".

If we want to let __init be callable on self it doesn't bother me  since it doesn't add complexity for subtyping. 

Still, __init is not like other __* methods. If that feels not pleasant we have to change the syntax of one of them.

**Comment by jclark** [comment]
What feels not pleasant is saying that it is a method, but then saying that everything that is true of methods does not apply to this. In that case, the reality is that it is not a method but a different kind of thing (i.e. a constructor) and the syntax should reflect that. Changing the name would not make it any more pleasant for me: it would need not to have a name (just as constructors do not have a name).

If you can at least call it using a method-call-expr on self, it is reasonable to think of it as a method, and reasonable to define it using method definition syntax.

**Comment by sanjiva** [comment]
Looks like the only usecase in Python is to call a super class' initializer? https://stackoverflow.com/questions/16126734/what-is-the-purpose-of-calling-init-directly

If so that doesn't apply to us because we're structurally typed and there's no super object concept.

I' m not against self.__init () being allowed - it just means someone can reuse the code in that method. So if that works then we're good:
- __init() remains as is and gets called automatically during object init time
- it cannot be called from outside the object
- it can be called from inside the object via self.__init() anytime

**Comment by sameerajayasoma** [comment]
If `__init()` is a regular method and can only be called from within the object, should we make it a `private` method? 

But private methods affect subtyping.

**Comment by jclark** [comment]
Conclusion today was to allow `__init` to be explicitly called only on self.
