### ISSUE TITLE
Clarification on typeof of simple value

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-spec#106]
Spec says:
```
When v is a simple value, the resulting typedesc will describe a type consisting of a single shape.
```

```ballerina
int s = 1;
typedesc a = typeof s;
```

Does this mean 'a' will describe '1' and only '1', and it does not have any reference to int-ness of 's'.

**Comment by jclark** [comment]
Yes and no.

It will describe 1 and only 1. But that 1 is a subtype of int, and not of any other basic type, so it _does_ reference the int-ness.

There will be a built-in method on typedesc to widen to the containing basic type. So if you do a.widen() or a.basicType() (or whatever we decide to call it), you will get a typedesc for int.

This is so that typeof is consistent with the static typing:

```
type E 1|2|3;
E x = 1;
typedesc<E> t = typeof x; // only works if typeof a simple value is a singleton
```
