### ISSUE TITLE
Clarification on the static type of Additive expression with operands of subtypes that contain both `xml` and `string`

### ISSUE THREAD

**Issue by chiranSachintha** [ballerina-platform/ballerina-spec#1087]
**Description:**
The [spec](https://ballerina.io/spec/lang/master/#additive-expr) says

```
the static type of one operand expression must be a subtype of xml and of the other operand expression 
must be a subtype of string, in which case the static type of the result is xml.
```
Why we can't allow the following kind of scenarios? Is there any special reason to disallow it?

```ballerina
type Strings "A"|"foo";

function errorFunction(string:Char|xml a, xml:Element|Strings b, xml<xml:Comment|xml:Text>|string c) {
    xml _ = a + a; 
    xml _ = a + b; 
    xml _ = a + c; 
    xml _ = b + b; 
    xml _ = b + c; 
    xml _ = c + c; 
}
```

**Comment by jclark** [comment]
Consider int|float + int|float. We don't allow that because there are two distinct operations: float addition and int addition. We require the code to be explicit about which one it means. Similarly there are two distinct concatenation operations: string concatentation and xml concatentation.

Just use `xml:concat`.
