### ISSUE TITLE
How should fromJsonWithType handle ambiguities?

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#1088]
JSON schema has any `anyOf` feature, which corresponds to union, and allows a schema that is equivalent to this.

```ballerina
type PetByAge record {
   int age;
   string nickname?;
};

type PetByType record {
   "Cat"|"Dog" pet_type;
   boolean hunts?;
};

type Pet PetByAge|PetByType;
```

But the problem is that this doesn't work when we try to use it with data binding:

```ballerina
json j = {
  "nickname": "Fido",
  "pet_type": "Dog",
  "age": 4
};

Pet pet = j.fromJsonWithType();
```

In this case  `fromJsonWithType` will return an error, because it does not know what inherent type to use for the `Pet` record it creates. Should it be `PetByAge` or `PetByDog`?

**Comment by jclark** [comment]
The cleanest thing in this case is I think to make the inherent type of the created value be the intersection of the two types i.e.

```ballerina
record {
   int age;
   string nickname?;
   "Cat"|"Dog" pet_type;
   boolean hunts?;
}
```

JSON schema provides `oneOf` and `anyOf`, where `oneOf` means it must belong to exactly one of the specified subtypes, and `anyOf` means it must belong to one of more of the specified subtypes. With this approach if a value has type `anyOf` A and B, and the value on the wire belongs to both A and B, then the inherent type of the constructed value will constrain the value so it continues to belong to A and B.

**Comment by jclark** [comment]
@hasithaa Any thoughts?

**Comment by jclark** [comment]
This is related to #544, so probably makes sense to do for Update 3.

**Comment by hasithaa** [comment]
> This is related to #544, so probably makes sense to do for Update 3.

Agree.

**Comment by Nadeeshan96** [comment]
I have some questions regarding this.

1. Since `fromJsonWithType works the same as cloneWithType`, `cloneWithType` should give the same behaviour. Am I right?
2. Though I could not find in the spec that restrict us to use intersection only with `readonly`, I cannot write like `anydata & json`, `int & byte`, `PetByAge & PetByType` in the code though the intersection is not empty. It gives an `unsupported intersection` compilation error. @MaryamZi Are we going to support it later?
3. Since #544 is related to this, before implementing this, can we come into the conclusion of what the general rule for intersection and defaults is?
4. `anyOf` passes if the value is at least one of the given types/schema. If we use the `intersection` as the inherent type of the created value, there are some cases which gives dissimilar behavior with our `union` and `anyOf`, where the intersection is invalid. Is this a problem?
Eg: Following passes given `anyOf` schema. But because the intersection is empty/invalid, in Ballerina the conversion may fail.
```bal
type A record {
    int x = 1000;
};

type B record {
    byte x;
};

type AB A|B;

public function main() {
    json j = {
        x: 10
    };

    AB val = checkpanic j.fromJsonWithType();
}
```

**Comment by jclark** [comment]
1. `cloneWithType` should work the same in this respect as `fromJsonWithType`
2. Intersection is not restricted to `readonly`. 
3. How does JSON schema deal with defaults combined with anyOf/allOf? Although #544 is related, I don't see why it needs to be resolved first.
4. If the type is `A|B`, the proposal is that *if the shape of the value is in both A and B*, then then inherent type is `A&B`. If the shape is in A but not B, then the inherent type is A and vice-versa.

**Comment by Nadeeshan96** [comment]
3. [JSON schema specification](https://json-schema.org/draft/2020-12/json-schema-validation.html#name-default) does not require that [annotation keyword "default"](https://json-schema.org/understanding-json-schema/reference/generic.html#id2) to actually do anything. In some of the implementations we can see it is being used for [generating JSON object from default values](https://openbase.com/js/json-schema-defaults), [setting default values during validation](https://ajv.js.org/guide/modifying-data.html#assigning-defaults), etc. [Here](https://json-schema.org/draft/2020-12/json-schema-core.html#name-distinguishing-among-multip) it says `The application programmer and the schema author need to agree on the usage`.

Another reference: `https://github.com/json-schema-org/json-schema-spec/issues/200#issuecomment-268181632`

I also looked at https://ajv.js.org/ implementation. There, though it gives output `{ x: 10 }` for the below code
```js
const Ajv = require("ajv")
const ajv = new Ajv({ useDefaults: true })

const schema = {
  type: "object",
  properties: {
    x: { type: "number", default: 10 },
  },
}

const validate = ajv.compile(schema)

test({})

function test(data) {
  const valid = validate(data)
  if (valid) console.log(data)
  else console.log("Invalid")
}
```
If we give the schema as
```js
const schema = {
  type: "object",
  anyOf: [
    {
      properties: {
        x: {type: "number", default: 10},
      },
    },
    {
      properties: {
        x: {type: "number", default: 10000},
      },
    }
  ]
}
```
it gives an error: `Error: strict mode: default is ignored for: data.x`.

4. For the Ballerina code in 4, if we add another line to print `typeof val` and it gives `A & B`, it is wrong if Ballerina `A & B` is invalid according to https://github.com/ballerina-platform/ballerina-spec/issues/544#issuecomment-643069011. So I thought #544 needs to be resolved first.

But rather than giving its type as `A & B`, we can give it as
```
record {
    byte x;
};
```
which is the intersection without having or considering default values. Should we do like this without failing the conversion if the intersection `A & B` is invalid?

**Comment by jclark** [comment]
We can now apply #1143 to this. The task is, given a

- a mapping value, and
- a set of zero or more record type descriptors,

to either give an error (that this is ambiguous) or

- determine a record type descriptor to use as the inherent type, and
- fill in any default values.

A similar process is done with a mapping constructor.

The task can be split into the following stages:

1. (This is already in the spec). Eliminate from the set any record type descriptors that are inconsistent with the fields names present in the mapping value, either because there is a field name that is not allowed by the record type descriptor or because the record type descriptor has is a required field name with no default that is not present in the mapping value. (In the mapping constructor case, this stage happens before determining the contextually expected type to be used for compiling the expressions specifying the values of fields.)
2. Eliminate from the set any record type descriptors that have field types that are inconsistent with the values in the mapping. (In the mapping constructor case, we use the static type of the expression to eliminate possibilities.)
3. If the set of record type descriptors is empty, then it's an error.
4. If there is more than one record type descriptor in the set, then we intersect them to produce another record type descriptor as described in #1143.  This also handles defaults as described in #544. This intersection may fail (i.e. result in a required field with type never). This means that this case is ambiguous and it's an error.
5. We then check that the record type descriptor constructed in step 4 has a default for every required field that is not in the mapping value.  If not, this means that the defaults are ambiguous and it's an error. Otherwise, we use the defaults from 
6. We also use the record type descriptor constructed in step 4 as the inherent type.

**Comment by jclark** [comment]
The idea of using intersections would be very challenging to implement, because if you have an intersection with N members there are potentially 2^N different inherent types that you might use.

Since our regular expressions support capturing, we have a similar problem with regular expressions: when multiple branches of an `|` could match we need to choose one.  For regular expressions, we are using first match (following JavaScript regexp semantics, which is what JSON schema uses).  Functional languages with pattern matching (e.g. CDuce) also use a first match semantics.

So I think a better approach is to use a first-match policy for cloneWithType/fromJsonWithType also.

**Comment by Nadeeshan96** [comment]
> So I think a better approach is to use a first-match policy for cloneWithType/fromJsonWithType also.

Here if the source value does not need conversion for a member type in the target union type of a `cloneWithType/fromJsonWithType` operation, should that be the target type or is it always the first convertible type?

For example
```bal
float x = 12.0;
int|float y = checkpanic x.cloneWithType();
```
Should the value of y be int `12` or float `12.0`?

**Comment by jclark** [comment]
Great question! The answer should be 12.0, but I'm not sure how to spec things to make it so.

I need to think about this.

**Comment by jclark** [comment]
Similar issue to #962 affects cloneWithType/fromJsonWithType.

**Comment by jclark** [comment]
What's worse is something like this:

```
json j = { x: 1 };
record { float x; } | record { int x; } v = check j.cloneWithType();
```

Do we try each alternative twice, first without conversions, and then with? That seems a bit excessive.

**Comment by Nadeeshan96** [comment]
> Do we try each alternative twice, first without conversions, and then with? That seems a bit excessive.

Yes, first we check without conversions, then with conversions.

**Comment by jclark** [comment]
> Yes, first we check all the alternatives without conversions, then with conversions. 

@Nadeeshan96 I am not sure exactly what you are doing, but consider:

```
json j = { x: 6.0, y: 12 };
record { int|float x; float y; } = j.fromJsonWithType();
```

If we try the whole fromJsonWithType operation without conversions, then it will fail (because the int value of j.y needs converting from int to float).  If we then try the whole fromJsonWithType operation with conversions, then the float 6.0 will get converted to int.

**Comment by Nadeeshan96** [comment]
> If we try the whole fromJsonWithType operation without conversions, then it will fail (because the int value of j.y needs converting from int to float). If we then try the whole fromJsonWithType operation with conversions,

Yes

> then the float 6.0 will get converted to int.

In the implementation, No. We do not convert if the given source value ( here `6.0`) belongs to one of the member types of a union (here `int|float`). The resultant value is `{"x":6.0,"y":12.0}`. This is same as the previous behavior we had had in the implementation before allowing ambiguous target types. With `2201.2.2` also, the operation passed giving `{"x":6.0,"y":12.0}`.

Btw we were writing the new behavior in the release note like this.
> When the user-specified target type was a union type consisting of multiple convertible types for a given source value, earlier `fromJsonWithType` & `cloneWithType` returned an error. Now for such user-specified target types, the operation succeeds without returning an error, returning a value whose inherent type is as follows. If the given source value belongs to at least one of the member types of the target union type, the inherent type of the returned value is the first found type to which the source value belongs. Otherwise, the inherent type of the returned value is the first convertible type in the union.

Please correct us if the new behavior needs to be changed.

**Comment by jclark** [comment]
>  first we check all the alternatives without conversions, then with conversions.

I don't think this is going to work well. Although this simple case produces the desired result:

```
json j = { x: 1 };
record { float x; } | record { int x; } v = check j.cloneWithType();
```

if you then change it to

```
json j = { x: 1, y: 2 };
record { float x; decimal y; } | record { int x; decimal y; } v = check j.cloneWithType();
```

then both alternatives require a conversion, so the first one will be chosen, and `x` will end up as a float not an int.
