### ISSUE TITLE
Annoying to remember when a ";" is required after a closing "}" for top level constructs

### ISSUE THREAD

**Issue by sanjiva** [ballerina-platform/ballerina-spec#1148]
This:
```
type Foo record {
  string blah;
};
```
and
```
function foo() {
}
```
are inconsistent in one requiring a ";" after the closing brace and the other refusing one. Can we fix this please?

**Comment by jclark** [comment]
There is a similar situation in C.

```
int x[] = { 1, 2, 3 };
int foo() { }
```

The rule is that if the declaration is of a kind that always ends with something in braces, then there is no closing semi-colon.

Same rule applies in class declarations

```
class Foo {
  map<string> foo = {
     x: 1, y: 2
  }; // semi-colon required
  function foo() {
     returns 1;
  } // no semi-colon allowed
};
```

which is the same as Java I think. 

You need the terminator in the first case because you can say

```
type Foo record {
  string blah;
}
| record {
   string blahblah;
};
```

whereas nothing can follow the `function` declaration.

In other words, the rule is that if the terminator is unnecessary because that kind of declaration permits nothing following the closing brace, then there is no semi-colon.

One could allow a top-level construct that was just an semi-colon, so that people could always put a semi-colon in - but that creates two ways of doing things, so I'm not sure it's an improvement.

Changing the language to always require a semi-colon would break all existing code and would be inconsistent with C family languages.

So short answer is no.

**Comment by jclark** [comment]
It turned out to be quite simple to always allow a terminating semi-colon: https://github.com/ballerina-platform/ballerina-spec/issues/1149#issuecomment-1217493308

Thanks for pushing on this!
