### ISSUE TITLE
Clarification on union of distinct error types 

### ISSUE THREAD

**Issue by Nadeeshan96** [ballerina-platform/ballerina-spec#1177]
**Description:**

What should be the output of following Ballerina code?
```bal
import ballerina/io;

type ClientError distinct error;
type ListenerError distinct error;
type PayloadBindingClientError distinct ClientError;
type PayloadBindingListenerError distinct ListenerError;

type PayloadBindingError PayloadBindingClientError|PayloadBindingListenerError;

public function main() {
    ClientError err = error ClientError("Whoops!");
    io:println(err is PayloadBindingError);
}
```
Since the `ClientError` does not belong to any member types if `PayloadBindingError`, give `false`
or
since the union type `PayloadBindingError` is not `definite`, consider it as equal to `ClientError|ListenerError` and give `true`?

**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

https://github.com/ballerina-platform/ballerina-lang/issues/36142

**Comment by jclark** [comment]
`err is PayloadBindingError` is false, because err has only the type-id for ClientError and not the type-id for PayloadBindingClientError nor for PayloadBindingListenerError.

If there is anything I need to change in the spec to make this clear, please let me know.

Definiteness is only relevant for construction.

**Comment by Nadeeshan96** [comment]
Got it. Thank you!
