### ISSUE TITLE
Mechanism to avoid making parameter name part of module API

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#120]
With the new approach to named parameters in 2019R1, all parameters are both named and positional.  This implies that parameter names are part of the API and changing a parameter name is backwards incompatible at the source level.  For the standard library and lang library, this would imply that we would need to finalize not just the names of the functions but the names of the parameters as well.

I would like not to have to decide on parameter names in time for 2019R2/R3.

I can see a couple of possibilities:

- temporary term hack that parameters for lang.* functions can be supplied only positionally
- some syntax to disable named parameter use for a particular parameter

**Comment by hasithaa** [comment]
In the current implementation, we use the `T.methodName` syntax for the built-in method and use `self` to refer to the self-value. (Similar to Object methods). Maybe we can continue the same until we figure out a way to solve this problem correctly.

**Comment by jclark** [comment]
@hasithaa Doesn’t solve the problem for parameters other than the first, and won’t work because it is necessary to be able to declare the type of the first parameter explicitly.

**Comment by hasithaa** [comment]
Yes, Agree with your point. 
Here is a random idea, Since we can provide values to a function call positionally, how about allowing access them positionally. i.e:

```ballerina
function name(T1, T2, T3) returns T4 {
  T1 a = name[0];
}
```

It looks weird though. And Not sure, how this works with Documentation syntax, Maybe we can treat them positionally too.

**Comment by jclark** [comment]
An alternative rule that is a bit ad hoc, but might work quite well: if the name of the parameter is a single character, then it can only be called positionally.

**Comment by jclark** [comment]
Here is what Swift does:

https://useyourloaf.com/blog/swift-named-parameters/

**Comment by jclark** [comment]
Here are two options:

1. Like Swift. Parameters can specify one name or two names (separated by space): a local name and an external name. Specifying one name is equivalent to specifying that name twice. The local name can be accessed as a variable within the function. The external name is used by the caller when invoking the parameter by name.  The external name can be `_` to mean that the parameter cannot be specified by name.

2. Make parameter name have visibility. A parameter can only be supplied by name if its parameter name is visible in the function or method call expression. By default parameter names, like other names, have module-level visibility. But a parameter in a public function can use the `public` keyword to indicate that its name is visible to other modules. If a parameter is declared as public, then all later non-rest parameters must be declared as public.

I think option 2 will work better for us than option 1.

**Comment by hasithaa** [comment]
I personally like,  Option 1, as it is similar to syntax we have for field-binding-pattern. 

```
field-binding-pattern :=
   field-name : binding-pattern
   | variable-name
```
It can be used to documenting parameters as well.

```ballerina
public function sum( int i : firstInterger , int j : secondInteger ) returns int {
 return i + j;
}
```

Option 2: I am OK with option 2, but it looks long because I have to repeat the `public` keyword every time. e.g:
```ballerina
public function foo (public int i, public int j) returns int {
  return i + j;
}
```

**Comment by sanjiva** [comment]
As the official representative of Morts, I find both of these approaches overkill and detestable. 

We're trying to solve a self inflicted problem of saying you can call anything this way and that way. And then we're upset that that means the param names are part of the contract.

I think we should just accept this and move on or go back to saying only defaultable params can be called by name. 

Specifically on the options: The Swift approach still has the same problem that you must get the external names "right" at some point. So all you're doing is kicking the can down the road. Option 2 just fries my mind to think of "public" as meaning you can use that name.

I think the model we had previously of only defaultable args being callable by name is better than these.

**Comment by sameerajayasoma** [comment]
I don't like option 2 as well. The usage of `public` keyword within the function param-list confuses people IMO. The difference between the two approaches is one has the allow-all by default strategy, the other one has deny-all by default strategy. 

IMO, the new approach that we've introduced in 2019R1 spec is better than what we had before. The API designers are allowed to make specific parameters required, some others defaultable. The caller has been given the flexibility to pass an argument to a parameter(can be required or defaultable) as a positional or a named arg.  There are some constraints, but more or less, this approach is very flexible and usable.  I prefer to keep this model. 

With this model, the parameter names are part of the function signature and changing a param name is a backward incompatible API change. What we are discussing here is a way to stop the caller from giving named arguments since parameter names are not finalized. I think this is a bit advanced usecase IMO. I prefer an allow-all strategy by default which forces the API designer to stop people from using named arguments for parameters case by case basis.

**Comment by jclark** [comment]
The question this issue is trying to answer is: when can a caller supply arguments positionally? Possible answers:

1. Always. This is what is in the spec now. Implies that all parameter names are part of the public API. 
2. Never. i.e. get rid of named parameters
3. A caller can supply a parameter name if the parameter name is visible to the caller
    1. a parameter without a visibility qualifier has module-level visibility
    2. a parameter may have a public qualifier, in which can it will have public visibility
4. User can supply parameter by name when it is defaultable.
    1. Implies that only the names of defaultable parameters are part of the public API of a module
    2. Does not allow use of parameter names for non-defaultable parameters

A related idea is #180.

**Comment by sanjiva** [comment]
Not sure whether you'd consider this related or not .. but right now we don't allow the rest param to be called by name. If one is giving a rest-arg then using a named calling syntax would seem natural instead of having to splice in the value using `...`. 

I'm not proposing removing the splicing, just noting that discriminating against the rest-param from being called by name seems in-elegant. 

The current semantics say that rest-param is a newly created list so there's not necessarily an optimization opportunity out of this (unless the compilation determines that function does not modify the list).

**Comment by jclark** [comment]
@sanjiva I made a new issue for that #181

**Comment by jclark** [comment]
General consensus if that least painful approach is to allow `public` to specify visibility of parameter names.

**Comment by jclark** [comment]
@hasithaa  @sanjiva This has some platform implications. The command-line parsing of main should pay attention to which parameter names are public: public parameter names should turn into named options; non public parameter names should turn into positional arguments. It might also need to affect http dispatch, with only public parameter names being exposed in the URI.
