### ISSUE TITLE
Ballerina Specification haven't mention about how to add ` character inside a Regex pattern

### ISSUE THREAD

**Issue by SasinduDilshara** [ballerina-platform/ballerina-spec#1221]
In the current Ballerina specification, under the topic of `Regular Expression`, It's not mention about how to add ` character inside a regex pattern.

The way to do this is Use **${"\`"}** inside the regex pattern, But this is not mentioned in the `Regular Expression section` in the Ballerina specification.

**Comment by jclark** [comment]
> The way to do this is Use **${"\`"}** inside the regex pattern, But this is not mentioned in the `Regular Expression section` in the Ballerina specification.

Where do you get that from?

Within a string-template-expr, you can do this, because ``"`"`` is an expression that evaluates to a string containing a single backtick.

The ways this works with regular expressions is covered by 

- https://ballerina.io/spec/lang/2022R4/#section_5.2.5
- https://ballerina.io/spec/lang/2022R4/#section_6.6.3
- https://ballerina.io/spec/lang/2022R4/#section_10.1

Specifically 5.2.5 says:

> the type of both the arguments and the return value of the returned function is B

This means that in the case of regexp, the type of the interpolated expression must be also be a regexp. So that approach does not work for regexp.

The way to get a backtick in a regexp is to use a regexp [NumericEscape](https://ballerina.io/spec/lang/2022R4/#NumericEscape) i.e. `\u{60}`
