### ISSUE TITLE
What should be done to the xml declaration?

### ISSUE THREAD

**Issue by Nadeeshan96** [ballerina-platform/ballerina-spec#1225]
**Description:**

The spec says the xml template expression is parsed using the production content in the W3C XML Recommendation. Currently at the compile-time, the xml declaration is considered as a regular XML processing instruction. But [according to the xml information set](https://www.w3.org/TR/xml-infoset/#infoitem.pi), it should not be. Hence, what should be done to the xml declaration?

We can think of some options like
1. Creating an xml processing instruction from the xml declaration found in the xml template expression  and put it in the xml value (current behaviour).
2. Disallowing xml declaration inside xml template expressions.
3. Allowing to have a valid xml declaration inside xml template expressions. Using that only to parse the xml content and not including it in the xml value.

**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

https://github.com/ballerina-platform/ballerina-lang/issues/39598#issuecomment-1457617909

**Comment by jclark** [comment]
The current behavior is certainly wrong:  [PITarget](https://www.w3.org/TR/xml/#NT-PITarget) does not allow `xml` as a value. So syntactically an XML declaration is not a processing instruction.

Since the spec says that the template expression is parsed as Content, the behavior that the spec requires is 2 (Disallow the XML declaration within an XML template expression).

**Comment by Nadeeshan96** [comment]
Got it. Thanks!
