### ISSUE TITLE
Expected behavior when there is a `panic` from within an async function call

### ISSUE THREAD

**Issue by ayeshLK** [ballerina-platform/ballerina-spec#1227]
**Description:**
As per the James' ballerina reference slides when there is `panic` from within an application, the application should terminate immediately. But, when there is a panic from within an async function call the behavior is not as expected.

Consider the following program:
```ballerina
import ballerina/io;

public function main() {
    _ = start async1();
}

isolated function async1() {
    int counter = 0;
    while true {
        io:println("This is async-1");
        if counter == 2 {
            _ = start async2();
        }
        counter += 1;
    }
}

isolated function async2() {
    int counter = 0;
    while true {
        if (counter == 10) {
            io:println("panicing from async-2");
            panic error ("async2 should exit now");
        }
        io:println("This is async-2");
        counter += 1;
    }
}
```

When we run the above program, even though the `async2` function panics the program does not get terminated.

@MaryamZi / @warunalakshitha is this the expected behavior ?

**Comment by hasithaa** [comment]
This is clear in the specification, but you have to derive the behavior by reading topics 7.3.2 Workers, 7.6 Start, and 7.7 Wait Action. The start action of asynch1 will run on a new strand, and panic will cause the strand to complete abnormally. It does not affect the strand that called the start action unless you wait for the future.

> As per the James' ballerina reference slides when there is panic from within an application, the application should terminate immediately. 

This statement is generally correct, as it is the expected behavior for most applications. However, users have the freedom to trap the panic and handle it differently. Therefore, the panic must reach the entry point (such as the main function) to terminate the application.
