### ISSUE TITLE
Give any|error and anydata|error names?

### ISSUE THREAD

**Issue by sanjiva** [ballerina-platform/ballerina-spec#127]
We say any|error and anydata|error a lot. Should we consider giving this a name?

**Comment by jclark** [comment]
We should recall the reasons why `any` or `anydata` does not contain `error`: it is because we want users to explicit about when a function returns an error. Also these cases are treated specially my message send and message receive. In general other functions may choose to give special treatment to errors, and that is confusing unless the possibility of error is made specific.

The name for `any|error` should be a bit longer and less friendly than `any` so people are not tempted to misuse it instead of `any`. We could perhaps design it as a pair with the type for #74.

**Comment by jclark** [comment]
Decided not to do this.
