### ISSUE TITLE
Relax rules on list and mapping constructor with no contextually expected type

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#143]
The spec currently says this is an error. But there is no contextually expected type for the first arg of a method call, which would make something like this an error:

```
[1, 2, 3].forEach(x => io:println(x))
```
That does not seem reasonable to me.

**Comment by hasithaa** [comment]
In the above example, If we go with most restrictive rules, we can consider the type of the array as `(1|2|3)[3]`, and where's x' type is `1|2|3`. 

`var x = [1,2,3];` is not allowed right now.  Instead type of the x can be inferred as `(1|2|3)[3]` or int[3] or int[]. But going with the most restrictive rule  `(1|2|3)[3]` gives some freedom. 

But we need more than that when dealing with simple basic values. i.e `var y = 1;`  Type of y can be inferred as 1, int, byte, json. The current rule is to go with the matching simple basic type, instead of singleton type.

**Comment by jclark** [comment]
I think the rule for var is the right one. The point of the rule is to make mutation work sensibly. If you don't want to mutate, then use final or freeze, and then you won't get the widening. We should follow the same approach for this issue.

Thus for list and mapping constructors, I would propose we infer a type T[] or map<T> where T is the union of the widened types of the members, where widening widens any simple type to its basic type.

A disadvantage of this rule if that it doesn't work for empty list or empty map. I think it is reasonable in that case to require a contextually expected type.

A more restrictive rule will not work for mutation.

**Comment by jclark** [comment]
Another point to remember is that all the lang.array and lang.map functions are treating the self argument as a T[] or map<T>.
