### ISSUE TITLE
Make E[n] work for xml type

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#200]
Should return n-th member of the sequence or an empty xml sequence if there is no such member.

**Comment by jclark** [comment]
`E[n]` should be an error if n is out of range for two reasons:

- consistency with array and particularly string
- when `E` is a subtype of `xml<xml:Element>`, result type of `E[n]` should be `xml:Element`

**Comment by rdhananjaya** [comment]
```x.<book>/<author|editor>[0]/<firstName>```

since ```x.<book>/<author|editor>[0]``` is `xml<xml>|error` should the navigation syntax stop from here? I mean syntax wise should we emit an error since after index access this is no longer XML. Or do we consider the whole navigation expression as a single unit operating on XML value? At the moment I have modeled this similar to index and field access 
(```((x.<book>)/<author|editor>[0])/<firstName>```)

**Comment by jclark** [comment]
`E/<author|editor>` is `xml<xml:Element>`.

Where do you get `error` from?

**Comment by rdhananjaya** [comment]
`x.<book>/<author|editor>[0]` I understand this as for each element `book` in x, get children sub-sequence matching `author` or `editor` and from this sub-sequence select first item. Flat map resulting sub-sequences into a sequence.

this "select first item" part may return an error (previously assumed to return an empty sequence)

**Comment by jclark** [comment]
`E[n]` out of range would panic, as with arrays and strings.

**Comment by jclark** [comment]
So result type of `x.<book>/<author|editor>[0]` is xml:Element.

**Comment by rdhananjaya** [comment]
> `E[n]` out of range would panic, as with arrays and strings.

Ack, I mistook it for error type. Panic resolves my confusion.

**Comment by rdhananjaya** [comment]
Since I wanted to have [0] to be right-associative with `<author|editor>` I made the `/<author|editor>[0]` to be a single unit returning a `xml<xml>`. As a single element sequence is an element I think this is fine. 

We need to improve this `xml<xml>` to `xml<xml:Element>` when we have the built-in subtype implemented.

**Comment by jclark** [comment]
`xml<xml>` is the same as `xml`.

`x.<book>/<author>[0]` returns the first author of every book i.e.

```
xml`<book><author>A1</author><author>A2</author></book>
<book><author>B1</author><author>B2</author></book>`.<book>/<author>[0]
== xml`<author>A1</author><author>A2</author>`
```

as in XPath.  See

https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/proposals/xml/xml.md#xpath-background

**Comment by jclark** [comment]
We should have a method that uses the XPath semantic of returning an empty sequence for an out of range index e.g. `x.book<author>.nth(0)`.

**Comment by jclark** [comment]
We decided to stick the semantics of out of range to return empty sequence rather than panic.
