### ISSUE TITLE
Can we allow function-body-block in an arrow-function-expr?

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-spec#21]
I am aware that a function-body-block is allowed in anonymous function expressions and only an expression is allowed in an array-function-expr. 

```ballerina
public function main() {
    var f = foo();
    io:println(f.call(5));
}

function foo() returns function(int) returns int {
    return i => { int k = i * i; 
                         return randomFunc(k);
                       }    
}
```
At the moment, I need to have an anonymous function expression to support the above requirement which is verbose IMO.

**Comment by jclark** [comment]
I don’t think this is a good idea. We considered it while designing the arrow function syntax.

One key difference between the compact arrow function syntax and the full anonymous function syntax is that with the former the return type is always inferred, whereas with the latter the return type is optional, defaulting to (). This makes sense when the body of the former is an expression and of the latter a block, because the language often infers the type of an expression, but typically does not infer the type of a block, but defaults the return type to nil, consistent with the implicit nil return from falling off the end of the block.

Another problem is that the arrow syntax becomes unreadable with large, complex blocks, which would be allowed by this proposal.

In the particular example you give, the arrow function syntax can, of course, be used by writing the body as an expression. I think a better long-term direction to go is to improve the expressiveness of expressions (for example, by adding expression syntax to bind variables or like this https://gcc.gnu.org/onlinedocs/gcc/Statement-Exprs.html), which can reduce verbosity in many contexts.

**Comment by sanjiva** [comment]
@sameerajayasoma shall we close this issue? I also agree with James that we should not change this.
