### ISSUE TITLE
"transaction" block being "experimental"

### ISSUE THREAD

**Issue by lafernando** [ballerina-platform/ballerina-spec#266]
The "transaction" block is still in the experimental level for jBallerina 1.0. The GA version of this is considered as a production-ready version of Ballerina, and thus, having transaction support in the language would be critical. Especially in the case of local transactions, this should be a stable feature. 

We can possibly only make the services based distributed transaction feature experimental, and give a special flag to enable this. Now at this moment, with just any transaction block usage, the coordinate service is started, regardless of whether we use it or not. 

The suggestion is to make the "transaction" block a stable feature for the local transaction functionality, and also possibly the XA transactions as well.

**Comment by hasithaa** [comment]
@lafernando @jclark I have moved this issue from ballerina-lang, as this is related to ballerina-spec.

**Comment by jclark** [comment]
The stable parts of the spec have been through a detailed design review and refinement process, and have reached the stage where the design team has developed sufficient confidence in the design that we are ready to commit to it long-term. The preview parts of the spec are part way through this process. The experimental parts, including transactions, have not started it. There is accordingly no possibility of declaring transactions to be stable at this stage.

The issue is not whether transactions are important or not, but how mature the transactions design is.

Currently amongst major features that are not yet stable, XML is closest to being stable, followed by tables, so I would expect those to become stable before transactions.

**Comment by jclark** [comment]
I created an issue #267 to track transactions support.

Preliminary step is for @sanjiva to document update spec to match current implementation, which is issue #20
