### ISSUE TITLE
XML proposal discussion

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#288]
This issue is to collect comments on the [XML](https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/proposals/xml/xml.md) proposal

**Comment by SupunS** [comment]
This new XML proposal seems really strong and covers a lot of limitations that is there in the current implementation.

Would like to clarify a few grey areas that I came across. I have grouped them under the respective section of the proposal:

**Value Space**

- Would it be useful to have at-least some basic support of CDATA? May be a subtype and a constructor?
- Equality (==) for xml-elements - should it use the XML canonical format? (This is somewhat relates to my next question in the following section)

**Namespaces**

Referring to the following section: 

> **Maintaining prefixes with namespace attributes**
>
>When constructing a Ballerina mapping for the attributes of an XML element information item, the attributes mapping will contain
> - an entry for any namespace declaration that was actually present in the attribute's start-tag (and so in the [namespace attributes] infoset property), and
>- an entry declaring the namespace (computed from the [in-scope namespaces] property) for prefix p, if p is not xml and p is used as the prefix of the element information item or of one of its attribute information items.

What would be the behavior when p is used by a child element, but not directly by the element itself or its attributes? Sample:
```xml
xml x1 = xml `<foo xmlns:ns0="hhtp://ballerina.com">
                 <bar>
                   <ns0:baz>hello</ns0:baz>
                 </bar>
              </foo>`;
```
```xml
xml x2 = xml `<foo>
                 <bar xmlns:ns0="hhtp://ballerina.com">
                    <ns0:baz>hello</ns0:baz>
                 </bar>
              </foo>`;
```
If I extract the child element having name ‘bar’ from both x1 and x2, in the resulting xml values (say x3 and x4 respectively), Does the namespace attribute entry `xmlns:ns0="hhtp://ballerina.com"` present in the attributes mapping of both x3 and x4?
i.e: Does both results in:
```xml
<bar xmlns:ns0="hhtp://ballerina.com">
    <ns0:baz>hello</ns0:baz>
</bar>
```

**Improved Navigation**
- I believe this must have been discussed earlier, if so, pardon me for the reiteration.. I wonder why haven’t we gone down the path of using XPath (or a subset of it), rather than a new syntax, since XPath is more familiar and stabilized among the XML users in general.
- Will it support navigating using dynamic paths (i.e: expressions support in the navigation syntax) ? For e.g: element name or the namespace part (of the element) comes from a variable. (Once use-case is: the namespace or the fully-qualified attribute name is extracted from one XML, and wants to filter-out elements with the same name in another XML - A somewhat common scenario)
- Support for wildcard matches? e.g.: All elements whose name starts-with/ends-with/contains “foo”.
- Any plans of adding filtering based on attributes?

**Comment by jclark** [comment]
Let me address each point in a separate comment.

On CDATA, I definitely don't want to add this. The right way to understand CDATA is just another way to escape characters. It should not be part of the data model any more than numeric/named character references. It's not in the XML Infoset (and so not in XPath, XSLT or XQuery).

**Comment by jclark** [comment]
When you construct the attribute map for an element, you add in enough namespace declarations to make each start-tag declare the prefixes that it uses.  In both your examples, this only affects the baz element, which uses the ns0 prefix wiyhout declaring it (use means use in a way known to the XML Namespaces Rec).

So x1 would become:

```xml
xml x1 = xml `<foo xmlns:ns0="hhtp://ballerina.com">
                 <bar>
                   <ns0:baz xmlns:ns0="hhtp://ballerina.com">hello</ns0:baz>
                 </bar>
              </foo>`;
```
and x2 would become:

```xml
xml x2 = xml `<foo>
                 <bar xmlns:ns0="hhtp://ballerina.com">
                    <ns0:baz xmlns:ns0="hhtp://ballerina.com">hello</ns0:baz>
                 </bar>
              </foo>`;
```

Nothing further happens on extraction so you get

```xml
                 <bar>
                   <ns0:baz xmlns:ns0="hhtp://ballerina.com">hello</ns0:baz>
                 </bar>
```
and

```xml
                 <bar xmlns:ns0="hhtp://ballerina.com">
                    <ns0:baz xmlns:ns0="hhtp://ballerina.com">hello</ns0:baz>
                 </bar>
```

respectively.

**Comment by jclark** [comment]
On C14N, I think it would be useful to have a function that did XML c14n on a xml value, assuming that it represented an XML document. However, you cannot compute the XML C14N for a child element, because in-scope namespaces are not propagated to child elements.

Apart from in-scope namespaces, I believe `==` will be the same as C14N-equivalence, although I have not checked in detail.

**Comment by jclark** [comment]
There are lots of reasons why XML Navigation is not XPath. I should add something about this to the proposal, since I suspect it will be an FAQ.

For most stuff that goes beyond what I've proposed, I would expect to use the filter function initially. If anything turns out to be very commonly used, we can try to come up with some more compact syntax.

**Comment by SupunS** [comment]
Thanks @jclark for the detailed explanation. 
Sorry I got, two more questions :) 

**1)**
One is a follow-up question regarding the namespace declaration (https://github.com/ballerina-platform/ballerina-spec/issues/288#issuecomment-535859009). In the same example, suppose I want to add an attribute `{"hhtp://ballerina.com"}status` to the `bar` element of `x1`. For that, I can get the `bar` element out and then add the attribute to it.

Here, `bar` element:
``` xml
<bar>
    <ns0:baz xmlns:ns0="hhtp://ballerina.com">hello</ns0:baz>
</bar>
```
But, given the namespace declaration `xmlns:ns0="hhtp://ballerina.com"` is now no longer in-scope of `bar` (and no parent child relationship), How would the prefix lookup happen? Wouldn't we need to store the unused namespace-declarations as well in every element, because it could be used at runtime, like in this case?

**2)**
Given that a namespace declaration would be in the same symbol space as imports, should a top-level namespace declaration be visible only to that particular source-file?

**Comment by jclark** [comment]
On point (2), given the syntactic similarity between import and xmlns, I think it should work similarly and so be visible only in the source file in which it occurs.

**Comment by jclark** [comment]
The prefix lookup uses the source namespace declaration:
```
xmlns “http://ballerina.com” as bal;
bar.bal:status = “done”;
```

This doesn’t preserve the prefix. If you want that, you would have to add a namespace declaration; otherwise a namespace prefix and declaration would get generated on output. This is not ideal, but I don’t see a better solution right now.

**Comment by jclark** [comment]
In your particular x1 case, on output it would use the ns0 prefix since that was already in scope.
