### ISSUE TITLE
Using new expression with streams

### ISSUE THREAD

**Issue by irshadnilam** [ballerina-platform/ballerina-spec#311]
**Description:**

The spec (2019r3) allows these use of `new` expression as follows
```
new-expr := explicit-new-expr | implicit-new-expr
explicit-new-expr := new type-descriptor ( arg-list )
A new-expr constructs a new object.
```
```
implicit-new-expr := new [( arg-list )]
```
However, with the current implementation, `new` expression is also allowed with streams.
The experimental doc currently doesn't mention anything about this.

Will the use of `new` be allowed with streams in future? If not how can streams be initialized?

**Comment by jclark** [comment]
For now, using `new` is the right thing to do. I'll mention this in the experimental doc.

I don't know what the syntax will be in the future.

**Comment by hasithaa** [comment]
@irshadnilam Sometimes back we decide to go with `new` expression (`implicit-new-expr` with no args) to create a stream value.  But we didn't allow `explicit-new-expr` syntax for stream, because we weren't sure, `new stream<T>()`syntax is future compatible. 

Shall we go with just 'new' for the moment? This will give a single way of creating stream value and it will be an easy fix if we need to change in the future.

**Comment by jclark** [comment]
`implicit-new-expr` only is fine for now, I think.
