### ISSUE TITLE
"json" does not mean what users expect

### ISSUE THREAD

**Issue by sanjiva** [ballerina-platform/ballerina-spec#328]
Can we add

```ballerina
type jsonobject map<json>;
```
to langlib? That will make life easier for many JSON users as most of the time they expect to get a JSON object and its less convenient to say map<json> for that doesn't feel as JSON'y.

**Comment by jclark** [comment]
In what module? If in it's in say the value module, then you would have to import that and use `value:jsonobject`. That doesn't strike me as a big improvement over `map<json>`.

I agree it would be nice if there was some way of making `map<json>` feel more first-class, but it's not straightforward to make it work well: as soon as you do member access on a `map<json>` you get back to `json` not `map<json>`.

**Comment by sanjiva** [comment]
How about a special known-to-the-compiler hack like we did with @TypeParam?

I agree and understand the benefit is rather shallow, but I think its still quite useful.

**Comment by jclark** [comment]
It sounds like you are asking for jsonobject to be a built-in type (like e.g. byte). If so, I don't see how it is an improvement to be able to write `jsonobject` instead of `map<json>`. It's the same number of characters. I also think map<json> is clearer, since what you have in Ballerina terms is a map not an object.  It would imply that users have to learn one more thing i.e. that `jsonobject` means the same as `map<json>`.

A arguable alternative to the current design would be to have

- `jsonvalue` mean what `json` now means
- `json` mean what `map<json>` now means

The advantage would be that our json type would be closer to what an average user thinks JSON means. But I think it would be confusing that when j is json, j.x gives you a jsonvalue rather than json. It would also be quite a disruptive change.

**Comment by jclark** [comment]
See also #417.

**Comment by jclark** [comment]
Alternative for `jsonvalue` would be `jsondata` analogous to `anydata`.

**Comment by jclark** [comment]
JSON RFC uses the term "JSON value": https://www.rfc-editor.org/rfc/rfc8259.html#section-3

**Comment by jclark** [comment]
@sanjiva prefers `jsonvalue`.

**Comment by jclark** [comment]
We decided not to do this.
