### ISSUE TITLE
"xml access expression" feature has become "experimental"

### ISSUE THREAD

**Issue by Maninda** [ballerina-platform/ballerina-spec#331]
**Description:**
In Ballerina beta test packs _xml access expression_ has become an _experimental_ feature. (i.e.: Need "--experimental" flag to run the code and the spec is subjected to change in future) But XML access is heavily used in Ballerina EI connectors. As this affects the stability of the Ballerina EI, that spec has to be finalized.

**Suggested Labels:**
lang, spec/improve, status/discuss
   
**Code sample that shows issue:**

```ballerina
xmlns "http://queue.amazonaws.com/doc/2012-11-05/" as ns1;
string|error queueUrl = response[ns1:CreateQueueResult][ns1:QueueUrl].getTextValue();
```

**Comment by jclark** [comment]
I changed it to experimental because I expect it to change (with `.` used for attribute access instead). However, I see that this creates a problem with the `--experimental` flag, because the rest of the XML support does not require this (even though it will also change).

So I think I should change this back.  What do you think @hasitha, @sanjiva?

**Comment by sanjiva** [comment]
I don't think we have a choice right now .. so yeah.

**Comment by hasithaa** [comment]
From semantic wise it not like lax typing, which can be backward-incompatible change.
