### ISSUE TITLE
Understand semantics of experimental lock statement

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#346]
There is page here with examples:

  https://v1-0.ballerina.io/learn/by-example/locks.html

but we need to understand the semantics in detail.

**Comment by sanjiva** [comment]
The old design document we had (but probably outdated):

https://docs.google.com/document/d/1-eKCfEqOLMx1OtQF28Mv2ogiaiS_1uIr_ArxKoNi9fU/edit#

**Comment by jclark** [comment]
I don't understand the compile-time aspect of the design. For example, in

```ballerina
type R record {
  int val;
};
R x = { val: 0 };
R y = x;
function foo() {
  lock { x.val += 1; }
}
function bar() {
  lock { y.val += 1; }
}
```
x and y refer to the same record, but the compiler won't know that at compile-time. (In this case it could figure that out, but in general it cannot know). How does the design deal with this?

**Comment by lankavitharana** [comment]
The current design doesn't figure that out, it only locks the reference location(not the value) so in the example you have given it won't identify this as the same value, hence locks won't work properly.

Other option is to keep the lock inside the value, in which case it will be hard to lock primitive types. That's why we went with locking reference location. But that fails here. 

I think we have two options, 
1) lock the value itself instead of the reference location(have to figure out a way to lock primitive types, maybe wrapper values when locks are used?)
2) Keep the reference locking and identify scenarios as above using data flow analysis.

**Comment by jclark** [comment]
I am not clear what you mean by "reference location". Is the lock associated with the symbolic access path (i.e. module/x/val)? Or is it associated with the variable?

**Comment by lankavitharana** [comment]
ok sorry, what I meant is variable(not the value). Sorry about the confusion.

**Comment by jclark** [comment]
Two more questions:

1. How do you deal with function calls within the lock statement? Are they restricted in anyway? If they are allowed, how can you know what variables they use?
2. How do you deal with parameters/local variables? Do you lock these? Does each function invocation have separate locks for its local variables or are the locks for local variables shared between all function invocations?

**Comment by lankavitharana** [comment]
answers to the questions,

1) function calls are allowed within lock statements, but we only track locks within a single function we don't consider global variables used in the called function(unless there is a lock statement in that function itself).
So if there is a lock inside called function, it will be treated as a separate lock in that function. But the locking happens per strand, so the same strand can acquire a lock for the same variable multiple times. So the called function will also try to acquire the lock, but since both function calls are in the same strand, it works.
2) In the current implementation, we don't support locking parameters or local variables, we only support below two scenarios.
 i) locking module variables
 II) locking object field variables within object functions itself. 
We had plans to implement parameter and local variable locking, but we faced some conceptual complications(basically couldn't finalize the spec for that) and couldn't finish that within the timeline.

**Comment by jclark** [comment]
I think I now understand the module variable case.

For the object field case:

1. is it just for fields accessed via `self`?
2. are the locks associated with the object (the value) or the object type?
3. is there one lock for the whole object or one lock per field (for fields that are accessed in the lock statement)?

**Comment by lankavitharana** [comment]
Answers for the questions
1) Yes
2) Locks are associated with the value, not the type. (because we can create multiple instances of the object and they should act separately) 
3) There per field locks. 
If I explain more, in object field locking, we keep lock for each field inside the object value itself. So two attached functions trying to lock two different fields in the same object at the same time is possible.

**Comment by jclark** [comment]
What happens if a field or module variable is sometimes accessed within a lock statement and sometimes not?

Given that function calls are allowed within a lock statement, I guess there is the possibility of deadlock at runtime. If so, what happens in the event of deadlock?

**Comment by lankavitharana** [comment]
for the first question, we only guarantee safe concurrent access only if the variables are handled in lock statements, otherwise, they are just normal variable access and we cannot guarantee safe access.

For the second question, yes even though we are using two-phase locking(which avoid deadlocks only in single function scenario), there are scenarios where there can be deadlocks, Below is an example(which is in the doc Sanjiva shared)
```ballerina
int value1 = 9;
int value2 = 7;

function main(string[] args) {
   worker w1 {
       lock {
           value1 = value1 + 1;
           testFunction1();
       }
   }
   worker w2 {
       lock {
           value2 = value2 + 1;
           testFunction2();
       }
   }
}

function testFunction1() {
   lock {
       value2 = value2 + 2;
   }
}

function testFunction2() {
   lock {
       value1 = value1 + 2;
   }
}
```
At the moment we cannot detect this and this will be an actual deadlock.

**Comment by jclark** [comment]
1. I was wondering if you gave a compile-time error if a variable is used sometimes in a lock statement and sometimes not.
2. When the deadlock occurs at runtime, do you try to detect this (and perhaps cancel one of the deadlocked strands) or does the program just hang?

**Comment by lankavitharana** [comment]
1) At the moment no, but can't there be any valid use cases like that? for example below code
```ballerina 
int a = 0;
function foo() returns int {
  worker w1 {
    lock {
      a += 1;
    }
  }
  worker w2 {
    lock {
      a += 1;
    }
  }
  _ = wait {w1, w2};
  a += 1;
  return a;
}
```
where accessing the variable inside a lock and outside a lock is valid. Anyway at the moment we don't detect this. 
2) We don't have mechanism at the moment to detect this at runtime. So program just hang.

**Comment by jclark** [comment]
See #357 for the issue on what the syntax/semantics should be.
