### ISSUE TITLE
Query proposal discussion

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#355]
This issue is to collect comments on the [Query](https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/proposals/query/query.md) proposal.

**Comment by grainier** [comment]
> A query-expr is not restricted to constructing lists. The type of value constructed is determined as follows:
> 
> 1. If there is a contextually expected type that allows only one basic type of structure, then the contextually expected type determines what is constructed.
> 
> 2. Otherwise, it constructs the same kind of thing it is iterating over. In other words the type of the in expression in the foreach-clause determines what is constructed. To make this work in an extensible way with objects representing collections, we will need a richer Queryable interface similar to Iteratable that allows for construction. This could also support queries that mutate collections (see below)

According to above;

```ballerina
type Person record {|
   string firstName;
   string lastName;
   string country;
|};

type UKPerson record {|
   string firstName;
   string lastName;
|};

Person[] personList;
```

1. What will be the type for `x`, is it `map<T>`, `Person`, `map<T>[]` or `Person[]`?
```ballerina
var x =
   foreach var person in personList
   where person.country == "UK"
   select {
       firstName: person.firstName,
       lastName: person.lastName,
       country: person.country 
   };
```

2. Since there's no contextually expected type, and select clause doesn't match with the type it is iterating over, is the type of `x` going to be `map<anydata>`?
```ballerina
var x =
   foreach var person in personList
   where person.country == "UK"
   select {
       firstName: person.firstName,
       lastName: person.lastName,
   };
```

3. Is this a valid scenario? If valid, how? and are we going to have `limit 1` (i.e for output rate-limiting) kind of syntax?
```ballerina
UKPerson ukPerson =
   foreach var person in personList
   where person.country == "UK"
   select {
       firstName: person.firstName,
       lastName: person.lastName
   };
```

**Comment by jclark** [comment]
Thanks for taking the time to comment. The point 2 you mention is written a bit confusingly,

When there's no contextually expected type, the *basic* type of the structure created is determined by the `in` expression, but the *member* type is inferred from the static type of `select` expression. So in both your cases 1 and 2, it constructs a list (rather than a table or map or stream) because the `in` expression is `personList` which has a static type that is a subtype of list. In case 1, the member type will be inferred from the `select` expression to be

```ballerina
record {
   string firstName;
   string lastName;
   string county;
}
```
so the type of `x` will be

```ballerina
record {
   string firstName;
   string lastName;
   string county;
}[]
```
which is equivalent to `Person[]`.

Similarly in case 2, `x` will have type:

```ballerina
record {
   string firstName;
   string lastName;
}[]
```

Case 3 would be a compile-time error. You could add syntax to specify that you wanted at most one of the results (e.g. `select first`), but then type would have to be `UKPerson?`, since there's no guarantee that there would be at least one.

**Comment by jclark** [comment]
I rewrote the bit you quoted. Hopefully it is clearer now.

**Comment by grainier** [comment]
Now it's clear, and thanks for your prompt reply.

Also, when designing Streaming query syntax, I suggest we should cover the following aspects as well;
- Windowing & Stream-Relation Joins (stream-stream, stream-table(or list))
- Windowing & Aggregation
- Windowing & pattern-matching (event patterns, event sequences)
- Union and Merge of streams (nice to have).

Further, with the proposed query syntax and its assignment, it doesn't give the user the feel of "forever running" nature of a stream. I think that's why we used `forever` blocks earlier.

```ballerina
	var x =
	   foreach var person in personStream
	   where person.country == "UK"
	   select {
	       firstName: person.firstName,
	       lastName: person.lastName
	   };
```
However, one suggestion is to simply allow `x` to be defined as a `stream`. So that, it'll allow processing to be done with a single pass over the data (i.e lists, tables...) or has temporal locality (i.e other streams, tumbling windows, etc...). With that, one can subscribe to that constructed stream to further keep on processing.

**Comment by jclark** [comment]
I added in a section to the proposal with a sketch of how the windowing aspect might work.

I envisage us having multiple kinds of queryable thing, of which list will be one and streams another. Queries should be able to combine multiple different kinds of queryable thing.

How is `forever` different from simply running the queries in a new strand (as with `start` or a named worker)?

**Comment by grainier** [comment]
It's a great idea to have multiple kinds of queryable things. It'll definitely open up a lot of potential with that API.

I think we came up with the idea of `forever` block since a streaming query as an expression does not provide the intuitiveness (i.e to show that query is running forever). Other than that, it's pretty much the same as running the queries in a new strand.

Also, with the below syntax, can you please clarify on;
```

window-clause :=
   "window" binding-pattern
   ["sliding"|"fixed"] duration-expression
   "on" timestamp-expression

```
1. Whether we are going to allow custom extensions for windows (and aggregators)? since we have so many at the moment (i.e. delay, external-time, hopping, unique-length, time, etc...).
2. If so, how are we going to support params for those extensions?

**Comment by jclark** [comment]
I haven't got far enough along on streaming query to answer your questions, but I would hope that we would get a lot of extensibility by allowing expressions in key places, since expressions can leverage the power of a full programming language, including functions.  We will have to dig into each feature in detail to see what is needed.

**Comment by gimantha** [comment]
Hi @jclark, @hasithaa and all 

I was going through the proposal again and thinking about starting on the implementation.

Please consider the following example from the proposal

```ballerina
var x =
   foreach var person in personList
   where person.country == "UK"
   select {
       firstName: person.firstName,
       lastName: person.lastName
   };
```

Using current implementation of foreach (where clause and select clause is not supported), if we want to  do the exact same thing which is done from the above example, we could do something similar to below.

```ballerina
Person[] temp = [];
foreach var person in personList {
    if (person.country == "UK") {
        temp.push({
            firstName: person.firstName, 
            lastName: person.lastName
        });
    }
}
var x = temp;
```
In case, we have a orderby clause, like in the following example,

```ballerina
var x = foreach var { firstName, lastName, country } in personList
   where country == "UK"
   orderby firstName, lastName
   select { firstName, lastName }
```
We could use our current foreach statement and write the following code to achieve the same.

```ballerina
Person[] temp = [];
foreach var person in personList {
    if (person.country == "UK") {
        temp.push({
            firstName: person.firstName, 
            lastName: person.lastName
        });
    }
}
temp = sortFunc(temp);
var x = temp;
```
I don't have a clear idea of `sortFunc` as of now. All it does is, sort the given collection.
So I think we could re-use our existing foreach  statement in de-sugaring phase to implement the new where clause and select clause. I have not thought much about using the existing foreach statement to implement joining and group by. It should be achievable with nested foreach statements.

Any feedback on the above approach is appreciated.

**Comment by jclark** [comment]
I am planning to do a new rev of this proposal that merges changes from upcoming Event Stream Processing proposal. Group will change completely as in that proposal. Join will also need rethinking: it’s not really nested foreach, but more read one side into a hash table and iterate over the other side.

I don’t know enough about the implementation to comment on the viability of your approach, but one point to be careful about is how to infer the type of the result. It should turn into:

```
record { string firstName; string lastName; } temp = [];
```

where the anonymous record type comes from the select expression.

The details of orderby will also need some more thought.

A good start would be `where` and `select` for lists. We can then build incrementally on that.

**Comment by gimantha** [comment]
> I don’t know enough about the implementation to comment on the viability of your approach, but one point to be careful about is how to infer the type of the result. It should turn into:
> 
> ```
> record { string firstName; string lastName; } temp = [];
> ```
> 
> where the anonymous record type comes from the select expression.
 
My bad.. Yes.. `temp` should be of type `record { string firstName; string lastName; }`
