### ISSUE TITLE
Add map:removeIfHasKey

### ISSUE THREAD

**Issue by lafernando** [ballerina-platform/ballerina-spec#381]
At the moment, if we use the "remove" function in maps, it will panic if the element is not there, and the same for the "get" function. In my view, we can simply just return T? (T being the constrained type), for the user to figure out if the entry was there or not. The current situation can mislead the design of an application to not to consider the entry not existing in the map, and in a edge case in the runtime, it can bring down the whole application - if we don't trap the error. 

Even though we have the [] operator the above suggested behavior corresponding to the "get" function, but we don't have one for "remove". So either we should have a "removeIfExists" operation, which would return T?, or else, update "remove" and "get" possibly to return the same. The first check if a key exists and remove is troublesome, since then we have to make sure it works as an atomic operation, with the usage of locks etc...

**Comment by jclark** [comment]
We are not making design changes to existing lang library functions at this point.

I think it’s reasonable to have a function that is like `remove` but returns `()` if it cannot do the removal because there is no such key. We already have a function called `hasKey` to test whether a key exists, so a consistent name would be `removeIfHasKey`; alternatively, `tryRemove`.
