### ISSUE TITLE
Declarative data transformations

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#39]
We need a declarative level way to describe transformations in terms of a data flow graph, so that we can provide a graphical interface.

Consider whether this can handle XProc use case.

Particular simple cases

1. Parse strings into structures
    1. DateTime/Duration
    2. Binary
    3. Xml
2. Hooks to call user-defined functions for arbitrary stuff

**Comment by jclark** [comment]
This [post](https://medium.com/@maheeka/data-transformations-with-ballerina-cc9c667e9d9) describes experimental implementation of `transformer` construct.

**Comment by jclark** [comment]
It looks to me to be pretty much equivalent to a function whose body consists of `return` followed by a mapping constructor, e.g.

```
transformer <Person p, Employee e> setCountry(string country) {
    e.age = p.age;
    e.name = p.firstName + p.lastName;
    e.address = p.street + p.city + country;
}
```

is doing the same as:

```
function setCountry(Person p, string country) returns Employee {
   return {
     age: p.age,
     name: p.firstName + p.lastName,
     address: p.street + p.city + country
   };
}
```

With arrow expressions, we already special case anonymous functions whose body is just `return E` where E is an expression, but in that case we infer parameter and return types, which we want to be explicit here.

C# allows [expression-bodied methods](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/expression-bodied-members) using `=>` i.e. instead of specifying the body as `{ block }` you can say `=> expr;`,  which is equivalent to `{ return expr; }`.  We could do something similar which would turn the above example into:

```
function setCountry(Person p, string country) returns Employee => {
     age: p.age,
     name: p.firstName + p.lastName,
     address: p.street + p.city + country
};
```

**Comment by sanjiva** [comment]
Yes this is a good model .. we had even previously some awkwardness about not creating return value first. I like this approach because you can't refer to the return value as an R-value at all.

IIRC there were some cases when we needed to return multiple values - never quite figured that out IIRC. To support that we will need to refer to which return is to be filled in.

From a UI design point of view its can be something like this:
![image](https://user-images.githubusercontent.com/2355900/67197784-314dfe00-f41b-11e9-8e9c-475bccb6b857.png)

Source: https://www.google.com/search?q=parallel+sets+graph&safe=active&sxsrf=ACYBGNSIP2g6ho1fXOYqRW-AuXu7D1-HQA:1571653491739&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiSy9bAka3lAhXRfn0KHZpGCycQ_AUIEigB&biw=1920&bih=969#imgrc=BgjfH6G_23Si3M: (clicking the image takes me to https://www.originlab.com/index.aspx?go=Products/Origin/Graphing and I can't see it there).

**Comment by jclark** [comment]
One nice thing about this approach is that you can create nested structures. In particular, you can handle creating multiple records by just returning a tuple of two records.  You can also look at this as a template: the constructor expression is in effect a JSON template for the value you want to create.

**Comment by sanjiva** [comment]
We can create a tuple:
```
function setCountry(Person p, string country) returns [Employee,City] =>
 [ {
     age: p.age,
     name: p.firstName + p.lastName,
     address: p.street + p.city + country
    },
   {
     name: p.city
   }];
```
But I'm not sure that will be enough .. in particular that means all assignments to the 2nd value must come after the first value. *Maybe* that will work.

However, IIRC we used to allow local variables too - as long as they were assigned and then read only and never updated. Pretty hard to do without those - a common transformation requirement is to call a remote API, get some data and use that in the result and its not practical to do that without variables.

**Comment by jclark** [comment]
What I am suggesting is purely functional, which I believe is the right thing for dataflow, so I would not describe it as involving assignment.  I think the semantics you are suggesting for local variables is equivalent to [let expressions](https://en.wikipedia.org/wiki/Let_expression), which fit into a functional paradigm.

**Comment by sanjiva** [comment]
Yes absolutely, that's what I meant as the requirement!

Purely functional is the perfect semantic for operators within the dataflow.

**Comment by hasithaa** [comment]
Our previous implementation was specific to mapping value transformation, mainly because that is the most common in the integration scenario due to JSON popularity. We haven't put much weight on XML, List or Table transformation.

I think the proposed syntax, works nicely with Mapping constructor, List constructor, XML expression and other constructor expressions.  

Another point to consider is, these transformations functions mostly applied with iterators or with functional iterations. In functional iteration case, we have to wrap it with another lambda in order to use them. So having built-in syntax (something like query syntax) is useful.  

```
Person[] pList = [];
Employee[] x = pList.map((p) => setCountry(p, "LK")); 
```
Some suggestoins;

```
Person[] pList = [];
var x = pList.map((p)=> {
     age: p.age,
     name: p.firstName + p.lastName,
     address: p.street + p.city + country
   });
```
```
Person[] pList = [];
var x = foreach p in person apply setCountry(p, "LK"); 
```

**Comment by hasithaa** [comment]
Sorry, Mistakenly closed the issue.

**Comment by hasithaa** [comment]
I like the proposed model, and it works well with mapping values. Only drawback is error handling. If we have to handle error, we have fall back to a full function. 

 Here are some points in the old design.
- We introduced Functional iterations initially the data transformations, and after removing the Transform statement, it evolved independently. Still, it can be used with this model.
- IIRC, there were several use-cases for local variables inside the transform statement. 
  - reuse values or results (of functional iterations, function calls)
  - As an intermediate step for value destructuring ( we didn't have binding patterns at that time)

It would be great if we can incorporate binding patterns with this design, because, most of the integration usecase requires to deal with open rerecords/JSON. But this has some challenges where we have to deal with "is-like" and error handling.

Array transformations are too common, but for those, mostly functional iterations are used.  XML transformation is a different league. Still the XML expression can be used with model. I feel, we can do with more with new XML desgin and that may require more than an expression.

**Comment by jclark** [comment]
For errors, we can at least allow `check` expressions, with the return type being `T|error`.

**Comment by jclark** [comment]
On binding patterns we could try to do something like #107.

**Comment by jclark** [comment]
#52 can also help extend what is possible within an expression.

**Comment by jclark** [comment]
Note that query expressions as discussed in #355 will combine nicely with this.

**Comment by jclark** [comment]
For 2020R1, we decided to do:

- expression-bodied functions (#395), and
- let expressions (#396).

We may also want to have a standard annotation that indicates that a particular parameter is the value being transformed, but we will wait for implementation experience to add this.
