### ISSUE TITLE
Assigment to xml attribute when xml val is not an element

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-spec#416]
**Description:**
XML attribute access https://github.com/ballerina-platform/ballerina-spec/blob/master/lang/proposals/xml/xml.md#attribute-access

Should we allow assigning to xml attributes (field access expressions), as other lax typed assignments are not allowed.

**Comment by jclark** [comment]
Currently:

```
map<string> m = {};
m.x = "foo";
```
is disallowed by this restriction:

> type descriptor for lvexpr must include field-name as an individual-type-descriptor

under field-access-lvexpr. The reason for the restriction was to deal with something like:

```
function foo(record { int x; int y; } r) { r.X = 1; }
```

But I think this restriction can be loosened: if the type descriptor for lvexpr doesn't include *any* individual-type-descriptor (e.g. it is `map<string>`, as in the XML case), then I don't see any need to disallow the field-access-lvexpr. In other words the requirement should be

> type descriptor for lvexpr must either include field-name as an individual-type-descriptor or not include any individual-type-descriptors

BTW, this is not really about lax static typing, which is to do with turning some kinds of compile-time errors into run-time errors.

@hasithaa, @sameerajayasoma Can you see any problem in loosening the restriction as described above?

**Comment by rdhananjaya** [comment]
Lax in the sense that similar to a JSON value, in an XML value we really don't know until runtime whether the value is an element or something else, hence attribute assignment might fail.

**Comment by jclark** [comment]
I misunderstood your question.

You can only assign to an attribute if you have a value of type xml:Element.

```
xml x;
x.att = "foo"; // compile-time error
xml:Element e;
e.att = "foo"; // ok
```

The first assignment cannot be allowed, because there would be no mechanism to report an error in the case that x was not an element. (One of the main points of the new XML design is to make xml:Element be a type, so that operations that make sense only on elements can be restricted at compile-time to elements.)

Also even in the xml:Element case, my previous reply isn't relevant, because the lvexpr is applying not to a `map<string>` but to an `xml:Element`.

**Comment by jclark** [comment]
I made the point about assigning to map<string> into a separate issue #417.
