### ISSUE TITLE
Starting a new strand within a lock

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#418]
Not clear how `lock` interacts with `start` (or more generally with calling a function that creates a named worked that outlives the default worker).

Relates #357.

It would be simple to say that lock only applies to the current strand, but that doesn't seem very useful. Best I can think of at the moment is that it's a runtime panic if this happens within a lock, on the basis that it is better to fail fast and predictably rather than allow data races.

**Comment by jclark** [comment]
Looking ahead to concurrency safety, I think pure/safe functions will be much more useful if we can allow a safe function to call a non-safe function under certain conditions, one of which would be that it does so in a lock.

**Comment by sanjiva** [comment]
Yes it will be, but if we allow that for pure functions that means global state can be changed by a called function. That could have a negative impact on some use cases of pure functions.

For (concurrency) safe functions of course being able to call a non-safe function in a lock is of course fine because that makes the callee safe.

**Comment by jclark** [comment]
In the call today, we decided, at least for now, to make it a runtime panic if you start a strand while a lock statement is executing.
