### ISSUE TITLE
Provide APIs to convert table and xml types to json

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-spec#482]
**Description:**
Currently `jsonutils` module in standard library provides APIs to convert an `xml` or a `table` to a `json` using
- `jsonutils:fromXml()`
- `jsonutils:fromTable()`

functions. 

We are planning to move these `jsonutils` library (along with the other utils libraries) since these APIs should be coming from the langlibs. These APIs are missing in langlibs. We should provide these APIs in ballerina langlibs in order to deprecate and remove the `jsonutils` module.

**Comment by jclark** [comment]
You can replace `jsonutils:fromTable` by `table:toArray`.

I suggest for now you rename `jsonutils:fromXML` to `xmlutils:toJSON`, since it's the other direction of  `xmlutils:fromJSON`. The transformation between XML and JSON that is done by jsonutils:fromXML and xmlutils:fromJSON is fairly ad hoc and does not belong in langlib.

**Comment by jclark** [comment]
Probably be best to unify xmlutils:fromTable and xmlutils:fromJson into a single fromAnydata function.

**Comment by sanjiva** [comment]
James can we move that to xml langlib and get rid of xmlutils? We're trying to get rid of *utils.
