### ISSUE TITLE
Provide a way to define connector icons through doc comments

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-platform/ballerina-spec#483]
There is a requirement to show icons for connectors/connector actions.

**Comment by jclark** [comment]
I suggest you use an annotation for this.

**Comment by nuwanbando** [comment]
@jclark should we create a new annotation only for the icon ? We can extract all other info from doc info for the low code work. We can restrict the icon only for the connector IMO.

**Comment by sanjiva** [comment]
James

**Comment by sanjiva** [comment]
Why is it not ok to have as structured way to associate an image with a (client) object and possibly (remote) methods? That's just another form of documentation and it can be nicely rendered as part of API docs too.

It doesn't make sense to me to say images are not part of documentation.

**Comment by jclark** [comment]
You are not using this information as documentation. It's metadata. Annotations provide a scaleable, controlled way to add metadata to code. Documentation does not.

I expect you will need lots of things to guide the low code experience.  Have one annotation with a record value, and then make icons and whatever else you need be fields of the record.

**Comment by sanjiva** [comment]
No Kavith explained this wrong - this is fundamentally not about low code.

Documentation has a lot of words (in English or other language) that also indicates to people what the code does. So it is not just "structured text" at all - it's structured to the extent of saying this is a param, this is the return etc. but after that it's all just text.

Being able to put an icon next to things is pretty fundamental in good docs these days .. we're not talking about generating good old man pages! We already support embedded images (as we extend GitHub MD) so this is similar but just identified as an image with an added semantics.

It can be done with an annotation but that's not the right approach IMO as this is simply part of docs.

**Comment by suhothayan** [comment]
In the low-code perspective, we are planning to read the doc comments to automatically generate the information and helper text for the UIs. If we are to use a separate annotation for the low-code it will be double the work for the developer. Therefore, either via docerina or in other forms, we should anyway need to pass the doc comments. 

In terms of the icons, I also see there is value if the doc site has connector icons. We need icons at both the client level and at each client function level. We can achieve this by having an icon section in the doc comment itself, name the file name there, and store the actual icon file in the resources directory of the module. But, If we are to use the annotation approach then we can use `@icon('<image name>')` annotation at both client and client function levels.

**Comment by jclark** [comment]
The way I look at it is that Ballerina provides two syntaxes for metadata:

- syntax A is a general-purpose syntax using `@` and mapping constructors
- syntax M a special-purpose syntax using lines beginning with `#` togethjer with MarkDown

For almost all use cases, syntax A is better than syntax M, in that it is extensible and type-checked. The only reason for the existence of syntax M is that syntax A would be extremely inconvenient  for writing structured text. We choose Markdown for syntax M, because Markdown is the most convenient, commonly used format for structured text.

So the right question to ask is not "Is an icon part of documentation?" but "Is the location of an icon something that is more suited for syntax M or for syntax A?", and the answer to that question is clearly syntax A: possible Markdown syntaxes would either build on the Markdown inline image format

```
![Alt text](/path/to/img.jpg "Optional title")
```

or embed an HTML `<img>` tag.  Neither of these provide any advantage over syntax A.

If you have a `@icon` annotation, there's nothing to stop your documentation generator making use of it.

**Comment by sanjiva** [comment]
I chatted with James about this:

James convinced me that it's not right to put an icon inside the documentation markdown. The reason is that docs are really just GitHub MD (except for recognizing a word in a list for param/return docs) and it doesn’t make sense to put additional metadata there. If the docs need to show an image that can be done already using GH MD tools (HTML or their syntax). 

Documentation is one kind of metadata that can go against certain items. We also have annotations as another kind of metadata.

We agreed however to make this a platform annotation as the icon can be used even by API docgen to do a nicer document.

**Comment by suhothayan** [comment]
Thanks for the clarifications, we'll use `@icon()` annotation for this.
