### ISSUE TITLE
Ambiguity between remote-method-call action and check-action

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-spec#494]
**Description:**

Consider the below sample:
```ballerina
function foo() {
    check a() -> b();
}
```

Above statement matches to two grammar rules:
- [Remote method call action](https://ballerina.io/spec/lang/2020R1/#remote-method-call-action) - A Remote method call action with a check-expression in lhs. 
i.e.:  `(check a()) -> b()` 
- [Checking action](https://ballerina.io/spec/lang/2020R1/#remote-method-call-action) - A checking action where action is a remote-method-call. 
i.e.: `check (a() -> b())`

**Suggested Labels:**

   
**Code sample that shows issue:**
Added above.

**Related Issues:**
N/A

**Comment by jclark** [comment]
So I think we need precedence table for actions like we have for expressions.

Since

```
x = check z.foo()
```

gets parsed as

```
x = check (z.foo());
```

I think

```
check a() -> b();
```

should get parsed as

```
check (a() -> b())
```

In other words `->` should have higher precedence then `check` for an action.

Precedence table for expressions also omits `check`. I think it should be in the same group as e.g. `typeof`.  WDYT?

**Comment by SupunS** [comment]
Yes, that sounds like a good solution.

I think `trap` expression/action is also in the same league as `check`, and has the same problem.
