### ISSUE TITLE
Langlib versioning

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#507]
Modules in langlib are versioned and you can import a langlib module with an explicit version.

But how would this really work in practice? The langlib implementation is closely tied to the implementation. Would it work to have a program using multiple langlib versions simultaneously.

There is also an issue with distinct types (#413). The language recognizes an object as being iterable if it has a distinct type defined by a langlib module. But what happens if there is a langlib module of a different version from the version included in the implementation? Should distinct types somehow be aware of module semver versioning?

**Comment by sameerajayasoma** [comment]
This issue is related to #237. With the package proposal, all the modules in a package share the same prefix (which is an `identifier`) and the modules in a package get the same version. 

Now all the langlib modules has the prefix `lang`, therefore they belong to the package `ballerina/lang`. Will this be a problem?

**Comment by jclark** [comment]
I think we need to continue to be able to version each langlib module independently.

**Comment by jclark** [comment]
Conclusion for Swan Lake is to special case langlib.

**Comment by jclark** [comment]
With #624, management of versioning is completely in the platform layer.

**Comment by jclark** [comment]
Conclusion from discussion today is that we don't version langlib.
