### ISSUE TITLE
Subtyping relationship between distinct types

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-spec#524]
**Description:**

Usage of primary and secondary type-ids to determine subtype relationship is not clear to me.

> The type denoted by a distinct-type-descriptor D, where D is distinct T, and d is the type-id of this occurrence of D, contains a shape s of an object or error value if and only if both T contains s and the set of type-ids of s contains d. 

Does this mean `set of type-ids of s` in the above statement imply the union of both primary and secondary type-ids?

```ballerina
type Foo distinct error;
type Fee distinct Foo;

function testFooError() {
    Fee e = Fee("message");
    Foo k = e; // Is this valid?
}
```

Do we consider the `distinct` type `Fee` to be a subtype of `Foo`?

**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

**Comment by jclark** [comment]
Fee is a subtype of Foo. The primary/secondary distinction does not affect subtyping. 

In your example, there are two type-ids t1, t2, where t1 is for the occurrence of distinct within the definition of Foo, and t2  is for that within Fee. When you create a value using Fee(), its type-ids will be {t1, t2} (t2 is the primary one, but that does matter for the purposes of typing); the value so created will belong to Fee because t2 is a member of {t1, t2} and will belong to Foo because t1 is a member of {t1, t2}.

The easy way to understand this is that a value has a type-id for every distinct type that it belongs to.

Please reopen if this does not answer your question.

**Comment by rdhananjaya** [comment]
It's clear now, thank you.

**Comment by sanjiva** [comment]
But we should not encourage this kind of code ;-).
