### ISSUE TITLE
Clarifying Type Ids

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-spec#527]
**Question 1:**
I'm having trouble understanding what the below sentence says, this is under `Type-Ids` subsection.

> A type descriptor that denotes a type that does not allow object or error values induces an empty set of type-ids and so is vacuously definite.

Is this talking about a distinct type definition where the values created with that type produce a non-empty set of type-ids such as `type FooError distinct error;`.

**Question 2:**

> A union type T1|T2 is definite if and only if both T1 and T2 are definite and the set of type-ids induced by T1 and T2 are the same.

```ballerina
type ErrorOne distinct error;
type ErrorTwo error;

type ErrUnion distinct ErrorOne|ErrorTwo;
```

Type definition `ErrUnion` is illegal as `ErrorOne|ErrorTwo` is not definite right?

`the set of type-ids induced by T1 and T2 are the same` mean T1 === T2 right? (Related to next question 4)

**Question 3:**
```ballerina
type Foo error<RecFoo>;
type Bar  error<RecBar>;
type Baz Foo|Bar;
```
Is `Baz` definite as both Foo and Bar contain the same empty set of type-ids, given error types are different?

**Question 4:**
```ballerina
type D distinct error;
type K D;
```
Will `K` contain all the type ids of `D` as it was there on `D`? 
Writing it as `type K distinct D` will create a new primary type-id `k` and D's type-ids will be secondary type-ids of K.

**Comment by jclark** [comment]
1. That sentence is talking about a type-descriptor such as `int`.
2. `ErrUnion` is not definite. It is only illegal in situations where a definite type-descriptor is required: such as in functional constructor.
3. It is definite. Being definite is about whether the type-descriptor implies a definite set of type-ids.
4. K will have the same type-ids as D. As usual `type A T;` makes `A` an alias for `T` with completely equivalent semantucs.

Please reopen if this does not answer your questions.

**Comment by rdhananjaya** [comment]
Please explain the answer for question 1.

**Comment by jclark** [comment]
The spec is defining a set of rules that specify for any type descriptor:

- when it is definite,
- if it is definite, what set of type-ids it induces

The rules have a separate case for each type-descriptor. In the "interesting" cases (like error, object, intersection, union), the section for that type descriptor specifies the rule for that case.

The sentence you quoted is giving the default rule that applies in "uninteresting" cases (such as `int` or `string`). The precise definition of interesting is: the set of shapes denoted by the type can contain errors or objects. The rule for uninteresting cases is that it is definite, but in an uninteresting way, because the set of type-ids is always empty.
