### ISSUE TITLE
Problems with creating objects of readonly type

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#535]
**Description:**

Say I have a record type with an object field, that has to belong to `map<anydata|readonly>`.

```ballerina
type Controller abstract object {
    function getValue() returns int;
};

type Config record {|
    Controller & readonly controller;
|};
```

Given that we can make a non-abstract object readonly only by making all of its fields readonly, is it possible to assign an object with no fields to `controller` here?

The following will work

```ballerina
type MyController object {
    readonly string id = "default";

    function getValue() returns int {
        return 0;
    }
};

public function main() {
    Config cn = {controller: new MyController()};
}
``` 

but what if `MyController` has no fields?

```ballerina
type MyController object {
    function getValue() returns int {
        return 0;
    }
};
```

I guess we can't make an object with no fields be readonly by default because that will disallow assigning any object that has fields to one that does not.

**Comment by sameerajayasoma** [comment]
Immutability is all about data. Object methods are considered immutable anyway.  If all the fields of a concrete object are readonly fields, object methods cannot modify them; hence the object is readonly.  If there are no fields in a concrete object, there are no fields for methods to modify; hence the object should be readonly IMO.

**Comment by jclark** [comment]
I have been finding our current terminology relating to object types makes for confused thinking. So, at the risk of confusing things further, let me try out some new terminology in this comment.

- where the spec would say "abstract object type", I will say simply "object type"
- where the spec would say "non-abstract object type", I will say "object class"

So in this terminology an object class is an object type plus an constructor (where the class defines methods that are attached to the object constructed by the constructor).

Your example then has:

- an object type named Controller, and
- an object class named MyController

Now let's add another object type:

```
type AbstractMyController abstract object {
   readonly string id;
   function getValue() returns int;
};
```

The type of the MyController class is AbstractMyController. Note that AbstractMyController is not a subtype of readonly, because AbstractMyController allows fields other than `id` to be non-readonly.

Before we consider your example, let's look at an easier case:

```ballerina
public function main() {
    MyController mc = new MyController();
    Config cn = {controller: mc };
}
``` 

Static type checking of expressions deals with types not classes, so from a static type checking point of view this is the same as:

```ballerina
public function main() {
    AbstractMyController mc = new MyController();
    Config cn = {controller: mc };
}
``` 

So this has to be a compile-time error, because `AbstractMyController` is not a subtype of `readonly` and so not a subtype of `readonly & Controller`, which is the declared type of the controller field of the `Config` type.

Now let's look at your example:

```
public function main() {
    Config cn = {controller: new MyController()};
}
``` 

The key question is what is the type of the expression `new MyController()`. My initial reaction was to say that it is the type of the MyController class; this would imply that the type of that expression was AbstractMyController. But that's not really satisfactory, because we know at compile-time that this expression will create a value with its readonly bit set. More generally, if C is a class with all its fields readonly (which includes the case of having no fields at all), then new C will create a value with its readonly bit set.

So what we need then to say is this: if C is a object class with all its fields readonly and the type of C is T, then the precise (as opposed to broad) type of new C is `readonly & T`.  Note that the presence of a readonly object field makes no difference here (a class with no fields and a class with one or more readonly fields are treated the same).

This points to a weakness in the language design: there is no way to define an object *class* that is readonly, in the sense that it is a subtype of `readonly`. We previous considered allowing `readonly object { ... }`, but we decided it would be too confusing to have both `readonly & abstract object { ... }` and `readonly object { ... }`. (I think we decided against this before we restricted `&` to abstract objects.) I think we should reconsider, because there is a clear difference: the former creates an object type and the latter creates an object class.

**Comment by sameerajayasoma** [comment]
I am using the same object types and object classes used in the previous comments. 

Based on @jclark's explanation, case 1 produces a static type error because the type of the `MyController` class is not a subtype of `readonly & Controller`. However, as explained in the previous comment, case 2 is okay. 

```ballerina
public function main() {
    // Case 1
    MyController mc = new MyController();
    Config cn1 = {controller: mc}; // Error

    // Case 2
    Config cn2 = {controller: new MyController()};  // Okay
}
```

If we had the support for `readonly object {...}`, then we could define `MyController` as follows, and then the above case 1 should compile with no type errors.

```ballerina
type MyController readonly object {
    readonly string id = "default";

    function getValue() returns int {
        return 0;
    }
};
```

**Comment by jclark** [comment]
@sameerajayasoma Yes, correct. Things work much better if we have `readonly object`: the type of `new C` is then `C` as one would expect.

**Comment by sameerajayasoma** [comment]
Yes, I also think we need `readonly object {...}`. It would be straightforward to write scenarios such as case 1 in my previous comment.

**Comment by jclark** [comment]
@sanjiva Are you OK with `readonly object { ... }`? We discussed today, and had consensus that we need it.

**Comment by sanjiva** [comment]
My understanding of the terminology:
- object type: The type part of an object class (i.e., defines a set of object values). An object type is defined using `abstract object`.
- object class: The implementation of an object type and defined using just `object`.
- object: An object value created by new'ing an object class.

Read-only is a concept that applies to a value. As a type, `readonly` means that all values of that type will be readonly. So if you intersect `readonly` to another type T, then you get the set of all values of type T which are read-only.

I'm ok with `readonly object { ... }` because that's saying that all object values created from that object class by new() will always be readonly.

**Comment by sanjiva** [comment]
Hmmm .. wouldn't:
```ballerina
type MyReadOnlyObject1 readonly object { .. }
```
and
```ballerina
type MyReadOnlyObject2 readonly & object { .. }
```
both describe the same set of values? The difference I guess is that it is not saying the unnamed `object { .. }` inside is creating a read-only value always. So really `readonly object` is its own special beast.

**Comment by sanjiva** [comment]
James pointed out we only allow type intersection for abstract objects, so no issue.

**Comment by MaryamZi** [comment]
Few follow up questions.

1. Will the grammar allow `readonly` immediately before `object` only?

```ballerina
type Foo client readonly object { 
};
```

or will it be similar to the current object-type-quals and allow different combinations like
```ballerina
type Foo readonly client object {    
};
```

2. With `readonly object`s I assume the user doesn't have to explicitly mark the individual fields as `readonly`?

Basically would the following will be valid
```ballerina
type MyController readonly object {
    string id = "default";
    map<string> config = {};

    function getValue() returns int {
        return 0;
    }
};
```

and the effective type for the same be
```ballerina
type MyController readonly object {
    readonly string id = "default";
    readonly map<string> config = {};

    function getValue() returns int {
        return 0;
    }
};
```

**Comment by jclark** [comment]
For 2, yes. Saying `readonly object` implies all fields are `readonly`.

For 1, since we do not constrain the order of `abstract` relative to `client`, I think the consistent approach is not to constrain the order of `readonly` relative to `abstract` and `client`.
