### ISSUE TITLE
Revise object type syntax and terminology

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#557]
I think it would be less confusing to use the following terminology:

- instead of _abstract object type_ say _object type_
- instead of _non-abstract object type_ say _object class_

The reason is:

- what we currently call an _abstract object type_ is not an abstract type, rather it is just a type (a set of values)
- what we call an non-abstract object type, is a type plus method definitions, which is conventionally caused a class

We based our terminology on Java. But Java has abstract _classes_, i.e. classes without the concrete definitions.

**Comment by jclark** [comment]
If we change our syntax to match, then it would be natural to change the object type descriptor syntax

* instead of `abstract object {...}` say `object {...}`
* instead of `object {...}` say `class {...}`

**Comment by jclark** [comment]
Still to do:

- Need a bit of intro about class in the object types section
- Stream types are classes
- Last para under type-ids needs rewriting
- Reference to abstract object in table of filler values
- Object constructor expression should use read-only from contextually expected type like other constructors
- Class definition needs to say something about distinct and type-ids 
- Need to clarify when type descriptors can refer to classes: intersection still talks about abstract types

**Comment by KRVPerera** [comment]
I think in OOP terminology the word `instance` is used interchangeably with the word `object`. This creates a bit of confusion adapting to Ballerina object type. So this question is probably due to my confusion.

#### In the section : "6.8.1 Object constructor"
After the new changes; although we say object construction we create an instance of a class using the object constructor. Is it correct to say object constructor create objects? Shouldn't the result of an `object-constructor-expr` be an anonymous class. Type or the shape of the result is an object. To me, this makes sense as `class-constructor-expr`.

**Comment by jclark** [comment]
@KRVPerera An object is an instance of a class. An object constructor does create an object because the result of evaluating an object constructor expression is a value of basic type object. However, an object constructor expression also creates a class: if you do typeof on the object constructed by the object constructor expression you will get the class. Hope this clarifies.

**Comment by KRVPerera** [comment]
Yes. Now it is clear. Thanks.
