### ISSUE TITLE
Should function qualifiers consider the order

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-spec#584]
**Description:**
Does the order of the qualifiers matters in fuction-def 

- eg1 : can we have `transactional remote` and `remote transactional` both for object method?

- eg2 : can we have `transactional resource` and `resource transactional` both for service resource function?

**Comment by jclark** [comment]
My instinct is to say `transactional resource` but `remote transactional`, but that seems inconsistent, so I would allow either order.

**Comment by rdulmina** [comment]
Okay will allow any order.

**Comment by MaryamZi** [comment]
@jclark, the implementation currently allows `transactional` and `isolated` in any order with `remote` and `resource`.

e.g.,
`isolated remote function`
`transactional resource function`

But the spec seems to allow `isolated` only after `resource` and `remote`, not before. Is this because `isolated`-ness is part of the type?

I assume it would be the same for `transactional` too?

**Comment by jclark** [comment]
Sorry, I forgot about this. `resource isolated function` doesn't read well at all, so I think we have to permit any order.
