### ISSUE TITLE
Usage of "transactional" on anonymous function expressions

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-spec#597]
I would like to know know whether we allow transactional keyword in anonymous function expressions. So are the following statements correct?

```ballerina
any anyFunc = transactional function ()  {
   ...
};

```
and 

```ballerina
transactional function ()  foo = function ()  {
   ...
};
```

**Comment by jclark** [comment]
We should allow the `transactional` keyword on anonymous function expressions.

In your two examples, the former is OK and the latter is not OK.

This applies also to function types: the function type should allow the transactional keyword. A function type with `transactional` is a subtype of the corresponding function type without `transactional`.

The other case is anonymous functions without explicit types (using `=>`) : in this case, whether the function is transactional should come from the contextually expected type.

**Comment by jclark** [comment]
@gimantha This comment of mine is not correct:

> A function type with `transactional` is a subtype of the corresponding function type without `transactional`.

That would not be type safe:

```
transactional function foo() {
  // here were are supposed to be guaranteed to have a transaction
}

type Fun function ();

function main() {
   Fun fun = foo; // would be OK according to my incorrect rule above
   fun(); // whoops: foo has been called without their being a transaction
```

The effect of the `transactional` qualifier on the function type is to reduce the contexts in which you can call the function; this is the opposite from the `isolated` qualifier, which increases the contexts in which you can call the function. So the subtyping relationship has to be the other way round.

This creates a problem with `function` by itself (in #7). We want `function` to contain all functions. The solution, I think, is to allow `transactional` only when there's a function-signature. Then say `function` by itself contains all functions (functions both with and without the function modifier).

**Comment by gimantha** [comment]
@jclark So according the original example which I posted in this issue, both cases will not be correct, according to your explanation. If someone wants to assign a function with `transactional` qualifier to a LHS expression, he always has to have `transactional` keyword on both LHS and RHS, right?

**Comment by jclark** [comment]
In your original example https://github.com/ballerina-platform/ballerina-spec/issues/597#issue-700970877, both cases are correct.

The first case is correct because `any` has `function` as one of its alternatives, and `function` **without a signature** allows both transactional and non-transactional functions. This is safe because you cannot do anything with a value that is typed as a function without a signature: you have to cast to a specific function type before you can call it.

The second case is correct because subtyping is the opposite way round.  A function that does not require a transaction context can safely be treated as a function that does require a transaction context.

But this would be an error:

```ballerina
function ()  foo = transactional function ()  {
   ...
};
```

You cannot safely cast away `transactional`, because what transactional is doing is restricting where a transactional function can be called.
