### ISSUE TITLE
Invoke resource functions directly

### ISSUE THREAD

**Issue by hevayo** [ballerina-platform/ballerina-spec#618]
**Description:**
Can we add support to directly invoke resource functions of a service in the same module. This will make it easier to unit test the resource function. If we are adding that support do we invoke already running instance of a service or we provide the support to instantiate the service object and invoke it. 

```ballerina
service hello on new http:Listener(9090) {

    resource function sayHello(http:Caller caller, http:Request request) {
        ...
    }
}

# Test function
@test:Config {}
function testServiceFunction() {
    http:Caller mockCaller = test:mock(http:Caller);
    http:Request mockRequest = test:mock(http:Request);
    // Directly invoking resource function as a function call
    // We can mock any object or parameters passed to the function
    hello.sayHello(mockCaller, mockRequest);
}
```

**Comment by jclark** [comment]
We will need the ability to invoke a service remote method (as they are now called - see #606) in order to be able to implement listeners in Ballerina. I just added an issue for this specifically: #620.

However, the problem here is to allow easy testing of services declared with a service declaration and the approach suggested here won't work well for that because of other changes we are making (such as #614, #606, #609). A better approach is to make it easy to create a client that connects to a service defined in the current module.
