### ISSUE TITLE
Map segments of hierarchical resource name onto parameters

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-spec#632]
In the old HTTP services implementation, a resource path can be written as a URI template, using the ResourceConfig annotation. e.g:
```ballerina
service orderMgt on httpListener {
    @http:ResourceConfig {
        methods: ["GET"],
        path: "/order/{orderId}"
    }
    resource function findOrder(http:Caller caller, http:Request req, string orderId) {
        // Implementation
    }
}
```
Created this issue to track, How we can adapt URI template support to the new service design.

**Comment by jclark** [comment]
The issue, as I see it, is to provide at the language level the functionality that was previously provided at the annotation level by using an annotation with a string containing a URI template.

With  #614, the language supports the concept that resources have a hierarchical name (as in a hierarchical filesystem), and that the hierarchy of names is handled with a corresponding hierarchy of services (just as a hierarchical filesystem handles hierarchical names with a hierarchy of directories). The problem then is to provide syntax/semantics for mapping from a segment of a hierarchical resource name onto something parameter-like.

The more challenging example than the one above is where the variable part of the URI template is in between fixed parts, e.g. `student/{studentsId}/course/{courseId}`.

**Comment by hasithaa** [comment]
@jclark @sanjiva @shafreenAnfar, If we allow `*` (Or another place holding char) in `relative-resource-path` grammar, we can allow this use case as follow. 

Consider a service with the following path templates. 
```
post /student/
get /student/bob/
get /student/{name}/class/{cid}/grade
```

We can conceptually write this as, 

```
service / on new http:Listener(8080) {
    resource function get student/bob () returns json {  ...  }

    resource function get student/*/class/*/grade (@http:PathParam string name, @http:PathParam string cid) returns json {  
        // Here  * will be matched to parameters with PathParam annotation. 
        // Listener implementation can decide how * and parameters are matched. For example, 
        // The first * will be matched to the first parameter with PathParam annotation: i.e. "name"
        // If users don't want PathParams, they can simply omit them.
        ...
    }

    resource function post student (json payload) returns json {}
}
```

This will be desugared into, 

```
service / on new http:Listener(8080) {
    resource service student = service {
        resource function post .  (json payload) returns json {  ... }

        resource function get bob () returns json {  ...  }

        // Everything else will be dispatched here. 
        resource service * = service {
            resource service class = service {
                 resource service * = service {
                      resource function get grade (@http:PathParam string name, @http:PathParam string cid) returns json {}
                 }
            }
        }
    }
} 
```
This design doesn't support advance matching patterns like `/student/{fname}-{lname}/` patterns, which we supported in the old design. String manipulation is required to support this use case.

**Comment by jclark** [comment]
I had a similar thought. Three further points.

First, I realized the desugaring is quite a bit more complicated than I had realized: https://github.com/ballerina-platform/ballerina-spec/issues/614#issuecomment-717628600. I might not want to specify this in terms of desugaring.

Second, I don't think we should need an `@http:PathParam` annotation here. The goal here is to do this as a language feature **without annotations**. A good solution should allow an HTTP service object to get path segments and/or query parameters into resource method parameters without the use of annotations. Each use of `*` should cause one parameter to be mapped from a path segment rather than from a query parameter: if you use `*`, then typically you want to know what `*` matched. This would apply to data parameters (i.e. subtype of anydata, not distinct objects) from left to right. For example:

```
resource function get foo(string x) { }
```
should get `x` from a query parameter, whereas:

```
resource function get *(string x) { }
````
should get `x` from a path segment.

Third, if that's the best semantic, then `*` is perhaps not the best syntax. Rather than:

```
resource function get student/*/class/*/grade (string name,  string cid) returns json {}
```

it is clearer to say:

```
resource function get student/{string name}/class/{string cid}/grade () returns json {}
```

This is built on-top of the simpler primitive that:

```
resource function get {string s}() { }
```

matches any resource name and binds the matched name to `s`.

**Comment by jclark** [comment]
There's also an argument for using square brackets rather than curly brackets for this based on analogy with computed named fields in mapping constructors https://ballerina.io/spec/lang/master/#computed-name-field e.g.

```
resource function get [string s]() { }
```

Another possibility would be `*` with a keyword:

```
resource function get * as string s() { }
```

Another possibility would be to use `*` by itself in the resource name, but then syntactically mark the parameters that refer to them:

 ```
resource function get *(string s from *) { }
resource function get student/*/class/*/grade (string name from *,  string cid from *) returns json { }
```

**Comment by jclark** [comment]
I guess the `from *` approach will work better from the point of view of also being useable as a syntax for service object types.

**Comment by shafreenAnfar** [comment]
Please note that at the moment we use the `*` to match everything that comes after a specific URL segment. For instance, annotating a resource with path pattern `/bar/*` would result in matching the following two request URLs to the same resource. 

```
/bar/foo
/bar/baz/foo
```

Also, IMO, I am not sure if possible but below syntax would be ideal. Because it is concise and readable. 

```
resource function get student/{string name}/class/{string cid}/grade () returns json {}
```

**Comment by sanjiva** [comment]
@jclark IMO the "from*" thing is way too complicated. I like the previous version you write, which is what Shafreen has put too. That also allows us to treat the function params as query params and to use optional arguments to indicate when particular params are not mandatory. Combined with ability to splice in a record type for params this is extremely powerful.

**Comment by jclark** [comment]
Our solution for this builds on https://github.com/ballerina-platform/ballerina-spec/issues/607#issuecomment-721459883. In a resource method, a path segment can use e.g. `[string s]` to specify a variable path segment, which will bind a parameter s of type string.

**Comment by hasithaa** [comment]
Consider the following hierarchical resources;

```
resource function get foo/baz/[string s]/bar () { } // A

resource function get foo/[string s]/[string s]/bar { } // B

resource function get foo/[string… i]/bar() { } // C
```

If we consider the path sets represented by each. A < B < C. This is something useful when describing an HTTP service.

But IMO this looks like overloading the resource path and We do not have overloading for methods. We need to explain this difference in the spec.

**Comment by sanjiva** [comment]
We ran into an issue in this approach with GraphQL.

The requirement comes up when supporting a GraphQL query like this:

```graphql
query {
  election (ID: "2019PRE") {
    province (ID: 3) {
      district (name: "Colombo") {
        divisions
      }
   }
}
```

I think we can write this using resource functions that return service objects.

However, our hierarchical resource syntax does not support this as we don't allow a particular resource path segment to have its own parameters - the params are for the whole path as a whole. In HTTP parlance, what we are missing in the hierarchical syntax is support for matrix parameters.

One way to solve this can be to do something like this:
```ballerina
resource function get foo/bar[string x]/baz/[int a]/hmm () {
}
```
Note the `/bar[string x]/` vs. `/[int a]/`. The prior is a parameter to the resource path segment `bar` and the latter is a variable path segment which must be an int. If the entire resource had params they would go to the function params as now.

@hasithaa @shafreenAnfar @sameerajayasoma @jclark 

Interesting reads:
* very old design note from TimBL: https://www.w3.org/DesignIssues/MatrixURIs.html
* https://stackoverflow.com/questions/401981/when-to-use-query-parameters-versus-matrix-parameters

**Comment by jclark** [comment]
I made @sanjiva's point in a separate issue #735.
