### ISSUE TITLE
Result of calling langlib methods on immutable values

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#646]
**Description:**
When langlib methods that create new values are called on immutable values, will the resultant value also be immutable?

For example, where `arr` is

> `int[] & readonly arr = [1, 2, 1];`

should the static type and the inherent type of the value created by

> `arr.filter(val => val > 1)`

be `int[]` or `int[] & readonly`?

Based on https://github.com/ballerina-platform/ballerina-spec/issues/551#issuecomment-646401361, do we only consider the element type and not the read-only bit of the array type itself?

**Related Issues:**
https://github.com/ballerina-platform/ballerina-spec/issues/391
https://github.com/ballerina-platform/ballerina-spec/issues/551

**Comment by jclark** [comment]
A langlib function like `filter` is parameterized the *member* type, so the static type of the collection wouldn't pick up the readonly (unless we do #521). But readonly does get pushed down to the member type. So, for example, if the static type T of the array is `readonly & (json[])`, then the most precise type M such that the T is a subtype of M[] is would make M be `readonly & json`  (since `readonly & (json[])` is subtype of `(readonly & json)[]`).

So in general if the argument type is `T[] & readonly` the static type and inherent type of the return value would be `(readonly & T)[]`.

**Comment by jclark** [comment]
#187 should say something about this.

**Comment by MaryamZi** [comment]
Noted, thank you.
