### ISSUE TITLE
Subtyping rules for service remote and resource functions

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-spec#669]
**Description:**
Since we are not considering `service resource functions` and `service remote functions` for the sub-typing relationship for the stage-2 of service typing implementation, should we ignore those `remote` and `resource functions` that are coming from type-reference in a `service class`.

```ballerina
type SType service object {
    remote function onMesage(anydata data);
    resource function get foo/bar();
    resource function get foo/[string j]();
};

// It's not required to implement referenced functions as they are all service remote or service resource functions.
service class SClass {
    *SType;
}
```

**Related Issues:**

**Comment by jclark** [comment]
It is only *resource* methods that are not being considered at this stage. For this reason, the spec does not allow resource function declarations in object types: https://ballerina.io/spec/lang/master/#object-member-descriptor. Extending this #608.

However, we *are* considering service remote functions for typing, although at this stage they do not provide any typing functionality beyond normal methods. Extending this is #609.

**Comment by rdhananjaya** [comment]
Ack, thank you.
Will update accordingly.

**Comment by hasithaa** [comment]
@jclark. I think the above rule works for client objects. But not for service objects. 

Similar to the resource function, we should be able to do data binding for remote function's parameters. Similarly, some services may require to define optional remote methods. (Looping @shafreenAnfar as well). None of these are achievable with the normal method subtyping rules.  

So for service, both remote and resource functions typing have to be validated using extensions for SL.

**Comment by jclark** [comment]
If you need more than what normal method typing gives you, then you will need to use a compiler extension until we do #609. But if you don't (and it is perfectly coherent to have Listeners that can be typed using what we have), then you can use normal method typing.

**Comment by jclark** [comment]
If you haven't the time to implement this, I would recommend simply not allowing remote methods in service object types (as the spec does for resources). This doesn't work from a spec perspective, because it makes #615 not make sense any more.

**Comment by hasithaa** [comment]
I agree with your point, But I feel it will introduce confusion if the service author has used both service typing and compiler extension to validate services. If they messed up it can produce conflicting errors. 

So I would say it is better if we can not allow remote methods in service objects until we figure out a solution for #609.

**Comment by jclark** [comment]
That confusion will not arise if you do not implement it. In any case, the only people affected would be those writing service types, which is for the moment only internal people.

It's important (to me at least) that the Swan Lake spec present a coherent language design; and I also thing that it is desirable for it to show how Listeners constrain the service type. Taking #615 out would be a step backwards. So, as far as the spec goes, I would like to stick to the plan we have had for the last few months.

Whether it's worth your implementing depends on whether any of the services that you are planning to ship have been designed to be able to be typed using the normal method typing. If they haven't, then there's not much point spending cycles implementing, especially since users cannot implement their own Listeners in Ballerina.

**Comment by hasithaa** [comment]
+1. We will continue with your suggestions.
