### ISSUE TITLE
Support for hierarchical package names

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#672]
The design for packages in #230 does not allow for hierarchical package names, because it always treats the first part of the module name as the package name. This restriction is turning out to be problematic.

**Comment by jclark** [comment]
One approach is to make the distinct between package and module explicit at the language level. This doesn't seem a good approach to me, especially for the `ballerina` organization. How the modules in `ballerina` are divided up into packages is an implementation detail that the user shouldn't need to be concerned with; the user should just see a clean hierarchy of modules.

This means that the platform needs to be a way to determine how many of the initial segments of a module name correspond to the package.

One approach is as follows: if you to have a package `x.y`, then package `x` includes something that says that its module `y` is external. Then to look up some package `x.y`, you first fetch the package `x`; if `x` says its submodule `y` is external, then you go fetch package `x.y`; otherwise, `y` needs to be part of `x`. To make this work with versioning, I think we would need to say that a package that depend on package `x.y` would also depend on package `x`.

**Comment by sameerajayasoma** [comment]
I prefer to make the distinction between the package and module explicit at the language level.  There is an impact on the import declaration, though. Users still see a program as a collection of modules, and a package is a way of grouping a related set of modules.  The `organization` plays a similar role in the language.

```
import-decl := import [org-name /] module-name [as import-prefix] ;
module-name := package-name [/ sub-module-name]
package-name := identifer-list
sub-module-name := identifer-list
identifer-list := identifier (. identifier)*
```
The following import declarations bring `lang.int`, `io`, and `http` modules into scope. These modules are default modules of respective packages. There is no change in syntax if you are importing the default module of a package. 

```
import ballerina/lang.int;
import ballerina/io;
import ballerina/http;
```

The following import declarations bring non-default modules into scope. 

```
import ballerina/io/file;
import ballerina/http/auth;
import ballerina/http/auth.jwt;
```

Here are a few advantages to this approach. 
1) The same module cannot exist in two different packages. I.e., no split modules.
2) Package name is explicit in the import declaration, which allows tools to lookup package repositories without an explicit dependency declaration in `Ballerina.toml` file.
3) Non-default module name parts fit nicely with the directory layout of a package. 

```
http/
├── Ballerina.toml
├── listener.bal
└── modules/
    ├── auth/
    └── auth.jwt/
```

**Comment by hasithaa** [comment]
I like, the @sameerajayasoma proposal. With this proposal,  handling dependencies within a package will look like bellow.  
```
PackageX
|-- ballerina.toml
|-- main.bal
|-- modules/
     |-- mod1/
     |     |-- a.bal
     |-- mod2/
           |-- b.bal
```

Case 1:   `main.bal` imports mod1
```
import packageX/mod1
```

Case 2: `b.bal` imports mod1
```
import packageX/mod1
```

**Comment by sameerajayasoma** [comment]
The [proposal](https://github.com/ballerina-platform/ballerina-spec/issues/672#issuecomment-743483217) can create an ambiguity with the import declaration `import x/y`. It could mean `org-name/module-name` or `package-name/sub-module-name`.

We could resolve this by mandating the `org-name` or something like `self/x/y`.

**Comment by hevayo** [comment]
I also favor if we can resolve the name collision with modules and packages. One approach is to detach module and package in the import statement. Following suggestion is based on JS syntax. 

```
import ballerina/io;
import http, auth from ballerina/http;
import grpc, auth as gAuth from ballerina/grpc;
``` 
The above will free `.` being a special character and the issue mention in previous comment.

**Comment by jclark** [comment]
Both @sanjiva and I prefer not to expose package names in the language.

It's a tradeoff between what is best for different groups:

1. For those writing simple applications, it's better not to expose the packages: they do not need to be concerned with how things are physically divided into packages; they deal with a simple, logical names.
2. For those writing libraries (i.e. packages that will be pushed to Ballerina central), it's better to expose the packages: this gives a more direct match between how they write library packages and how they import them.

For Ballerina, we have a consistent policy of preferring group 1 over group 2.

**Comment by sameerajayasoma** [comment]
This comment describes a package resolution algorithm that supports hierarchical packages names. This algorithm does not require the package name to be explicit at the language level.

## Key design decisions 
- Packages should be released independently of each other. For example, users should be able to release `ballerina/x` and `ballerina/x.y` independently of each other. 
- Packages with the same module are allowed to be pushed to a package repository. 
- Packages with the same module are not allowed in a package graph.

## Terminology 
#### 1) Package 
A Ballerina package is a collection of related Ballerina modules that are versioned and released together. A package is identified by an organization name, package name, and version. 

`package-name := identifier(.identifer)*`
#### 2) Module
A Ballerina module is a collection of ordered source files (.bal) in a single directory. 
- **Default module**: maintains the source files at the package root directory.  
- **Other modules**: maintains the sources inside the `modules` directory which is at the package root. Each top-level directory inside the `modules` directory becomes a Ballerina module. 

`module-directory-name := identifier(.identifer)*`

The module name is the package name joined with the module directory name. The default module’s name is same as the package name.

`module-name := package-name (. module-directory-name)`

#### 3) Package repositories
Ballerina packages can be stored in a package repository. It provides a mechanism to look up packages using the organization name, package name, and version. The version is optional when searching for packages:
- When the version is provided, the repository returns the exact version or an error if the requested package version is not available. 
- When the version is not provided, the repository will return:
  - The latest stable version  
  - The latest pre-release version when there are no stable versions
  - An empty list 

The ballerina development environment can be configured with one or more package repositories. Ballerina package system searches against these configured repositories to locate Ballerina packages. Here are some pre-configured package repositories.

#### 4) Platform distribution repository 
Each ballerina platform distribution comes with a package repository. It contains lang lib packages and other standard library packages. 

#### 5) Ballerina central 
Ballerina central is the package repository provided by the Ballerina community.

#### 6) User-defined repositories 
Ballerina development environment allows you to configure third-party Ballerina package repositories. If you want to use packages in any third-party repositories, add the package dependency to `Ballerina.toml` with the repository information. The package system does not automatically search packages in third-party repositories. 

#### 7) Importing modules
An import declaration specifies a module. Here `x.y.z` is the module name in the organization `foo`. 

`import foo/x.y.z;`

The package name is not explicit in an import declaration. It can be one of `x.y.z`, `x.y`, or `x`. The following sections describe an algorithm to resolve a package from a module.

#### 8) Package resolver 
The component that resolves package versions from dependencies declared in `Ballerina.toml` and from import declarations in source files. The resolver also handles version conflicts if multiple versions of the same package are present in the package graph. 

#### 9) Root package 
The package in which you want to run `ballerina build` or `ballerina test` commands. 

#### 10) Package graph
A dependency graph rooted at the root package. It contains the direct and transitive dependencies of the root package. 

#### 11) Initial Package graph
The package graph created from the dependencies declared in the root package’s `Ballerina.toml`. If there are no dependencies declared in the `Ballerina.toml` file, then the initial package graph is empty. The final package graph can be different from the initial graph if import declarations cannot be satisfied with the initial package graph. 

#### 12) Resolved package versions
There are two kinds of resolved package versions: 
1) **User-specified package version**: A version of a package in the initial package graph.
2) **Resolver-computed package version**: A package dependency version resolved by the resolver in an attempt to resolve the package from an import declaration.

During the version conflict resolution process, the resolver prefers `user-defined` package versions over `resolver-computed` package versions. This will ensure repeatable builds.

## Package resolution process

#### Resolving a package from an `import` declaration
Consider the following import declaration as an example. This section illustrates the algorithm to resolve the package that has the module `x.y.z`.

`import foo/x.y.z;`

##### Resolution algorithm
- The resolver first checks whether the module `x.y.z` belongs to a package in the initial package graph. 
  - Find packages whose names are prefixes of the module `x.y.z`. E.g., packages with names: `x`, `x.y` or `x.y.z`.
  - If there are such packages, then look for the module `x.y.z` in each package.
  - If the module is present in more than one packages, then reports an error,
  - If the module is present in exactly one package, then use that package. 
  - If the module is not available in the initial package graph, try to resolve using configured package repositories.
- For each configured package repository provided by the Ballerina development environment:
  - Package resolver attempts to get the latest version of each package that may contain the module. E.g., Package resolver attempts to get the latest version for packages `x.y.z`, `x.y`, and `x`.
  - If more than one package contains the module, then pick the latest version.  If there are packages with the same version, choose the package with the longest package name.
  - If there exists a package that contains the module, compare it with the package resolved by the previous package repository
    - If the previously resolved package and this package has the same name, then pick the latest version
    - If the previously resolved package and this package names are different, then pick the latest version.  If there are packages with the same version, choose the package with the longest package name.
  - If there are no packages found, continue to the next repository
- Report an error if none of the repositories contain a package that has the module. 
After completing this algorithm, use the resolved package and record it in the package graph as a `resolver-computed` package. 

Repeat the above algorithm for all unique import declarations. 
In the final package graph, check whether there are packages with the same module, in which case report an error.

**Comment by jclark** [comment]
Does this allow for a package to be split? For example, if we start-off, with `ballerina/unicode` as a single package, with multiple submodules, and then later split `ballerina/unicode.sort` off into a separate package.

What do you see as the advantages of this proposal over what I proposed in https://github.com/ballerina-platform/ballerina-spec/issues/672#issuecomment-742997530?

**Comment by sameerajayasoma** [comment]
This proposal allows for a package to be split. Your example works. 

Here are some differences between the two proposals. I am using labels `proposal J` and `proposal S` to refer to these proposals :) 

With `proposal J`, if you want to release `foo/x.y`, you need to release `foo/x` as well. `foo/x` has to have an entry that says something about the package `foo/x.y`. Later if you want to release `foo/x.z`, you need to release a new version of `foo/x` with both the entries. I prefer an approach that doesn't create such coupling between packages. This could be a nuisance for developers who want to push packages with hierarchical names. It's a usability issue.  With `proposal S`, you can release packages independently of each other. 

Task the following packages as examples:
- [ballerinax/googleapis.sheets](https://github.com/ballerina-platform/module-ballerinax-googleapis.sheets)
- [ballerinax/googleapis.gmail](https://github.com/ballerina-platform/module-ballerinax-googleapis.gmail) 
- [ballerinax/googleapis.calendar](https://github.com/ballerina-platform/module-ballerinax-googleapis.calendar)

If I want to create these packages, I would have to create another package `ballerinax/googleapis` and add these entries.  When a user import one of the above packages, we have to put two dependencies in `Ballerina.toml` to handle the versioning complexities. Say, I use `ballerinax/googleapis.sheets` in my code. There will be two dependencies in my toml file when I build it: one for `ballerinax/googleapis.sheets` and one for `ballerinax/googleapis`.

IMO, split modules are rare. There I prefer to allow people to push packages with such modules. The `proposal S`, suggests an algorithm that produces a repeatable build even with split modules. It reports an error only when there are more than one packages in your local dependency graph with split modules, which is pretty rare IMO.  I studied the resolution algorithms in Go and Java, and both similarly solve the problem.

**Comment by sameerajayasoma** [comment]
We (@sameerajayasoma, @hasithaa, @sanjiva) decided to go ahead with the approach described in the [comment](https://github.com/ballerina-platform/ballerina-spec/issues/672#issuecomment-747076745) with the following tweaks 

### Package repository
The invariant is that: for any two packages, `Pa` and `Pb` in a package repository, the latest version of `Pa` and the latest version of `Pb` MUST NOT contain the same module.

Here is an example: when you push the package `Pa` that has the module `m`, if the latest version of the package `Pb` contains `m`, then this is an error. You need to push a newer version of `Pb`, which does not have `m` to resolve this error.

#### Splitting a package into multiple packages 
Assume that a package named `x` contains the module `x.y`, and later you want to move the module `x.y` into its own package. In this case, you first need to push a new version of the package `x` that does not contain the module `x.y`. Then push the package `x.y` that contains the module `x.y`.

#### Merging multiple packages into a single package 
Assume a package named `x.y`, and you want to merge it with the package `x`. If you push a new version of the package `x` with the module `x.y`, then the above invariant is no longer true. 

To handle this situation, you need to mark the package `x.y` as `discontinued`. Here are the semantics of a `discontinued` package in a repository:
- You can request a discontinued module by providing the exact version, 
- Otherwise, the package repository MUST NOT consider discontinued packages. 

### Resolution algorithm
Report an error if there are split modules in the initial package graph. 

Step 1: For each import declaration:
- The resolver first checks whether the module `m` belongs to a package in the package graph. 
  - Find packages whose names are prefixes of the module `m`. 
    - E.g., when `m` is `x.y.z`, such prefixes are `x`, `x.y` and `x.y.z`.
  - If there are such packages, then look for the module `m` in each package.
  - If the module is present in more than one packages, then reports an error,
  - If the module is present in exactly one package, then use that package. 
  - If the module is not available in the package graph, try to resolve using built-in package repositories.

Step 2.1: For each import that specifies a module in `ballerina` organization:
- Let `Pd` be the latest package that contains the module `m` in the distribution repository.
- Let `Pc` be the latest-compatible package that contains the module `m` in the central repository. 
- If both `Pc` and `Pd` are not available, report an error. 
- If `Pc` is not available, then add `Pd` to the package graph.
- If `Pd` is not available, then add `Pc` to the package graph. 
- If both `Pc` and `Pd` are available:
  - If they both have the same package name, add the `latest(Pd, Pc)` to the package graph
  - Check in the central repository for a newer version of `Pd` that doesn't contain the module `m`. If such a package is available, add `Pc` to the package graph, report an error otherwise. This situation is rare and can be handled by Ballerina standard library developers when splitting or merging modules. 

Step 2.2: For each import that does not specify a module in `ballerina` organization:
- Let `Pc` be the latest-compatible package that contains the module `m` in the central repository. 
- If `Pc` is not available, report an error.
- If `Pc` is available, add it to the package graph.

#### Adding a package to the package graph
The invariant of the package graph is that the graph MUST NOT contain packages with split modules at any given time. Therefore, this invariant should be true even after adding a new package to the graph.
