### ISSUE TITLE
Why is that `error` is categorized under behavioral values

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-spec#699]
**Description:**
I can't wrap my head around why `error` is a behavioral value, and why we can't perform `DeepEquals` like operation for errors. 

**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

**Comment by jclark** [comment]
Three reasons:

1. An error value contains a stack trace. The stack trace is unique to the error value and is an array of objects.
2. Error can be used with distinct, which means an error value can have a type-id, which include a module id, which mean it’s not anydata, since anydata is supposed to be plain data that is independent of any program operating on the data. It simplifies the language to make the things DeepEquals work on be the same as anydata.
3. The only reason the language has error as distinct from record or object is to enable programs to behave differently when they encounter errors.

**Comment by rdhananjaya** [comment]
oh I think I get it now.
I think I was too focused on the word `behaviour`, as in behaviour of a function.

Thank you.

**Comment by jclark** [comment]
Right, “behavioural” really just means not plain data. I’m open to suggestions for a better word...
