### ISSUE TITLE
xml-element-descendants-step is defined in terms of non-existent function xml:getDescendants

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/ballerina-spec#701]
Semantics of xml-element-descendants-step is defined in terms of a function xml:getDescendants that does not exist in lang.xml

**Comment by jclark** [comment]
I would like to fix this by adding (and documenting) a `getDescendants(Element x)` function to `lang.xml` (we already have `getAttributes` and `getChildren`).

**Comment by jclark** [comment]
Decided to add getDescendants to lang.xml.

**Comment by pcnfernando** [comment]
Could you please clarify the output of the following? My confusion is whether the output should only contain the elements as per spec. Since the descendant of C is not an element.

> The descendants of an element are the children of the element and
 the descendants of those children that are elements, ordered so that
 each element immediately precedes all its descendants.
 The order of the items in the returned sequence will thus correspond
 to the order in which the first character of the representation
 of the item would occur in the representation of the element in XML syntax.

```ballerina
'xml:Element sampleXml = xml 
`<A>
    <B>
        <C>
            <!-- This is a comment -->
        </C>
        <D>
             Hi
       </D>
    </B>
</A>`

xml descendants  = sampleXml.getDescendants();
```

(A)
```ballerina
<B>
     <C>
     </C>
     <D>
     </D>
</B>
```

(B)
```ballerina
<B>
     <C>
        <!-- This is a comment -->
     </C>
     <D>
         Hi
     </D>
</B>
```

**Comment by jclark** [comment]
Descendants contains all descendants not just elements: “descendants of those children that are elements” means “descendants of those (children that are elements)” not “(descendants of those children) that are elements”.

**Comment by jclark** [comment]
I rephrased in a way that I hope will avoid the ambiguity.
