### ISSUE TITLE
Limited scope of type narrowing leads to code nesting

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-spec#73]
**Description:**

Consider an example, where you need to access text payload from an http response. 

```ballerina
public function simpleVersion() {
    http:Client ep = new ("http://example.com");
    (http:Response | error) rp = ep->get("/");
    if (rp is http:Response) {
        (string | error) txt = rp.getTextPayload();
        // 2nd level if block
        if (txt is string) {
            io:println("response.../n", txt);
        } else {
            io:println("error 2...");
            panic txt;
        }
    } else {
        io:println("error 1...");
        panic rp;
    }
}
```

In above code type narrowing rules lead to nested if conditions. But we can simplify the above code using `checkpanic`, but with that, the developer loses the ability to handle errors using custom logic.

```ballerina
public function usingCheckPanic() {
    http:Client ep = new ("http://example.com");
    http:Response rp = checkpanic ep->get("/");
    string txt = checkpanic rp.getTextPayload();
    io:println("response.../n", txt);
}
```

A possible improvement we can do is allow type narrowing on return/panic statements. 

```ballerina
public function improvedVersion() {
    http:Client ep = new ("http://example.com");
    (http:Response | error) rp = ep->get("/");
    if (rp is error) {
        io:println("error 1...");
        panic rp;
    }
    // Now rp is http:Response here.
    string | error txt = rp.getTextPayload();
    if (txt is error) {
        io:println("error 2...");
        panic txt;
    }
    // Now txt is string here.
    io:println("response.../n", txt);
}
```

The `continue` statement also used in a similar context, where a developer can avoid multiple nested conditions in a loop with a `continue` statement.

Thoughts?

**Comment by jclark** [comment]
I think the other way of doing this will have its own problems.

Most importantly, it reduces code readability, because the user has to consider a much larger region of code in order to know what type a variable.

It will also get complicated. Consider:

```
if x is T1 {
  if x is T2 {
    panic err;
  }
}
// x can be ~T1 | (T1 & ~T2)
```

Also if you want to do this properly, then you would need a way to say that a function never returns, so that `myPanic(e)` with `function myPanic(error e) { panic e; }` will get treated the same as `panic e`. In other words, the static type system of the language would need to add the concept of not returning.

Getting this specified properly would be a lot of work with questionable benefit. At this point, I think there are higher priorities.

**Comment by jclark** [comment]
See also #73.

**Comment by jclark** [comment]
I believe TypeScript does things the same way the spec currently does, but Kotlin does it the other way.

**Comment by jclark** [comment]
Note that with #74, we do now have concept of not returning.

**Comment by jclark** [comment]
This is a real pain, and I think we should fix it.

**Comment by ramith** [comment]
+1. Having lots of nesting quickly becomes very irritating when logic becomes relatively complicated.

**Comment by jclark** [comment]
Interesting case is:

```
int|boolean|string|() x;
if x is int|boolean {
   if x is int { return; }
}
else {
   if x is string { return; }
}
boolean? _ = x;
```
