### ISSUE TITLE
Is a variable reference expression an isolated expression if it refers to an isolated variable?  

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#732]
**Description:**
Currently, the implementation does not allow the following. 

```ballerina
isolated int[] stack = [];

isolated function push(int n) {
    lock {
        stack.push(n); // invalid attempt to transfer a value into a 'lock' statement with restricted variable usage
    }
}
```

`stack` in `stack.push(n)` is currently considered an invalid attempt to transfer in a value based on the following conditions in the spec.

> Transferring values into the lock statement is constrained: a variable-reference-expr within the lock statement that refers to a variable or parameter defined outside the lock statement is allowed only if the variable-reference-expr occurs within an expression that is isolated.

>  a method-call-expr is isolated if the expression preceding . is isolated, the expression for each argument in the arg-list is isolated and the type of the method being called is isolated.

We don't consider a reference that refers to an `isolated` variable as an isolated expression because a variable reference expression is considered to be isolated only 
> if it refers to an identifier bound by a let-expr to an expression that is isolated

Is this understanding incorrect? (Related discussion: https://github.com/ballerina-platform/ballerina-spec/issues/599#issuecomment-706827036)

Considering any such variable reference as an isolated expression can violate the isolated root concept, right?

```ballerina
isolated int[] stack = [];

isolated function push(int n) {
    lock {
        int[][] stacks = [stack]; // if allowed `stack` is no longer an isolated root?
    }
}
```

**Comment by jclark** [comment]
The concept is that the lock statement:

1. can read and write to the one isolated variable
2. apart from that, restrictions on transfers in an out must be followed

If the lock statement just does 1 (and does not transfer anything into or out of the lock statement) the value of isolated variable will necessarily still be an isolated root: it is not possible for there to be any new references into the isolated graph from outside (because that would require a transfer out); the value of the variable can only be set to something in the isolated graph or something newly created, so the value of the one isolated variable will continue to be an isolated root.

Allowing 2 also maintains the invariant.

**Comment by jclark** [comment]
My intuitive model is that the lock statement is like a container that within its scope restricts the program to operate on the graph rooted at the isolated root; this container then do I/O using transfers in/out.

**Comment by jclark** [comment]
I added a sentence to the spec to clarify.  If this is still not clear, please reopen.

**Comment by MaryamZi** [comment]
Thank you.

So the examples I've mentioned should be allowed. But in case there were attempts to transfer in/out other values incorrectly, those attempts would result in errors, which would be sufficient to ensure the isolated root continues to be an isolated root?

**Example I**
```ballerina
isolated int[] stack = [];

int[][] allStacks = [];

function push(int n) {
    lock {
        int[][] stacks = [stack]; // OK
        allStacks = stacks; // error, OK if it was `stacks.clone()`
    }
}
``` 

**Example II**
```ballerina
isolated int[][] stacks = [];

function push(int[] n) {
    lock {
        stacks.push(n); // error for `n`, OK if it was `n.clone()`
    }
}
``` 

In these scenarios, the error would never be for reading from/writing to the isolated variable.

I think the issue in the implementation is that we consider accessing the isolated variable itself as an attempt to transfer in rather than an attempt to read from/write to it.

Shouldn't the rules for transferring out still apply though?

**Example III**
```ballerina
isolated int[][] allStacks = [];

isolated function get(int index) returns int[] {
    lock {
        return allStacks[index]; // error, OK if it was `allStacks[index].clone()` or ` allStacks.clone()[index]`
    }
}
```

**Example IV**
```ballerina
isolated int[][] allStacks = [];
int[][] alsoAllStacks = [];

function set() {
    lock {
        alsoAllStacks = allStacks; // error, OK if `allStacks.clone()`?
    }
}
```

Also, extending the function/method call scenario to any arbitrary function, I believe the following can be allowed since the `lock` statement ensures exclusive access to `stacks` until the `update` call is done and a clone of `n` is passed as the argument.

**Example V**
```ballerina
isolated int[][] stacks = [];

function push(int[] n) {
    lock {
        update(stacks, n.clone()); // OK, error if `update(stacks, n)`
    }
}

isolated function update(int[][] x, int[] y) {
    x.push(y);
}
```

**Comment by jclark** [comment]
**Example I**
This is an error, since you are transferring out something that is not the value of an isolated expression.

With `stacks.clone()` it would be fine.

**Example II**
This is an error, since you are transferring in `n`, which is not an isolated expression.

> I think the issue in the implementation is that we consider accessing the isolated variable itself as an attempt to transfer in rather than an attempt to read from/write to it.

That's not correct. I see now that the spec wasn't clear about that.

> Shouldn't the rules for transferring out still apply though?

Let me rework the clarification because I see it is still not clear. 

**Example III**

Error because return is a transfer out, and it is transferring out something not isolated.

**Example IV**

Error because assignment to a variable (other than the isolated variable) is a transfer out and it's not isolated.

**Example V**

You are transferring in `n`, but you are doing it in an isolated expression, so that's fine.  Since the update function is `isolated` the call is fine, and the invariant is maintained (because `update` can't "escape" from its arguments). I believe the spec allows this.

**Comment by jclark** [comment]
Hopefully this time it's clear. Please reopen if not.

**Comment by MaryamZi** [comment]
This is clear now, thank you.
