### ISSUE TITLE
Configurable variables should be implicitly final

### ISSUE THREAD

**Issue by sanjiva** [ballerina-platform/ballerina-spec#759]
Currently we say the value assigned to a configurable variable is readonly. However the variable can be reassigned!

Note that we say function parameters are implicitly final. Configurable values are essentially parameters for the whole program.

**Comment by sameerajayasoma** [comment]
Consider the following example: 

```
configurable string & readonly accountSId = ?;
configurable string & readonly authToken = ?;
configurable string & readonly fromMobile = ?;
configurable string & readonly toMobile = ?;

service / on new http:Listener(8080) {
    resource function get foo() returns error? {
        string message = "";
        twilio:Client twilioClient = new ({
            accountSId: accountSId,
            authToken: authToken
        });
        var result = check twilioClient->sendSms(fromMobile, toMobile, message);
    }
}
```
The service object will be inferred as isolated because it does not have any mutable fields. 
But the resource function `foo` won't be inferred as `isolated` since it accesses the non-final module-level variables.   Therefore the `http:Listener` will not execute the resource function `foo` on multiple threads. 

The compiler can potentially issue warnings here (It doesn't do that at the moment). The solution is the mark all configurable variables as `final`. 


It is very common to use configurable variables within resource functions. We could simplify this use case if we treat configurable variables as implicitly final. There is no need to modify configurable variables anyway.

**Comment by jclark** [comment]
@sameerajayasoma That an argument for making them implicitly `readonly` also.

**Comment by hasithaa** [comment]
If the `configurable` qualifier implies the final and readonly, then we can change the following parser rule. 

`module-init-var-quals := (final | isolated-qual | configurable)*`

to 

`module-init-var-quals := (final | isolated-qual )* | configurable `

**Comment by jclark** [comment]
Agreed to make this a priority because of the interaction with isolated.

We will make configurable imply readonly and final.
