### ISSUE TITLE
Support rounding a float value to n number of decimal points

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-spec#760]
**Description:**
ATM, we don't have a direct API to round a float value to the `n` number of decimal points. There is a workaround like below that suggested [here](https://ballerina-platform.slack.com/archives/C47EAELR1/p1603452230106300)

```ballerina
import ballerina/io;

public function main() {
    decimal input = 12.6789890;
    decimal d = input * 100;
    decimal rounded = d.round() / 100;
    io:println(rounded);
}
```

However, I think this workaround is cumbersome to the user and it would be better to have a single API like below:
```ballerina
import ballerina/io;

public function main() {
    decimal input = 12.6789890;
    decimal rounded = input.round(2);
    io:println(rounded);
}
```

**Affected Versions:**
- Swan Lake Alpha 2

**Comment by jclark** [comment]
Related to #322.

**Comment by jclark** [comment]
I would at least add to lang.decimal:

```
function round(decimal d, int fractionDigits) returns decimal;
```

It is not clear to me whether round is well-defined as an operation on (binary) float type, since `round` is dealing with base 10, and float is base 2. I think round for float makes more sense in the context of float to string conversion. See #770.

It also makes sense for float to decimal conversion. Not sure how to expose that.

**Comment by hasithaa** [comment]
Since we already have the `round` function, to make it backward compatible, `fractionDigits` must have a default value. `lang. float` also has the `round` function, we have to make it consistent too.

**Comment by jclark** [comment]
@hasithaa I think for decimal at least we can simply default the fractionDigits argument to zero. The precision of the result comes from the fractionDigits. i.e. `decimal:round(1.00d)` is `1d` not `1.00d`.

Note this is a good example of a theoretical incompatibility that I don't think we should worry about. If somebody has written:

```
function decimal round(decimal) rounder = decimal:round;
```

this will be broken by adding a default argument. But the chances of one of our external users having done this in a real program is so small that it should not prevent us from making the change.

**Comment by hasithaa** [comment]
> Note this is a good example of a theoretical incompatibility that I don't think we should worry about. If somebody has written:
> 
> ```
> function decimal round(decimal) rounder = decimal:round;
> ```
> 
> this will be broken by adding a default argument. But the chances of one of our external users having done this in a real program is so small that it should not prevent us from making the change.

Yes, Agree.

**Comment by jclark** [comment]
Interestingly, python has the same `round` as we are proposing, and the implementation works by converting to string

https://github.com/python/cpython/blob/5ab745fc51e159ead28b523414e52f0bcc1ef353/Objects/floatobject.c#L940

**Comment by jclark** [comment]
Currently lang.decimal says decimal:round is the same as IEEE roundToIntegralTiesToEven. IEEE allows the exponent of the result of this to be positive. So if you have a decimal  x with exponent q > 0, the roundToIntegralTiesToEven(x) will have exponent q. So according to `1e3d.round()` ought to return `1e3d`. But in fact jBallerina makes `1e3d.round() returns `1000`, i.e. it has exponent 0.

This is fortunate because we want `decimal:round(x,fractionDigits)` to have an exponent of `-fractionDigits`.

**Comment by jclark** [comment]
The description for `float:round` doesn't fully address the subtlety that arise from the fact that floats are not reals. There's

1. a real number that is close to the operand and integral multiple of the 10<sup>-fractionDigits</sup>, and
2. there is a floating point value that is close to that real number

Do you pick (2) based on closeness to (1) or closeness to the operand? How does this tie in with the way `toString` does rounding? We want `x.round(f).toString()` to show no more than f digits are the decimal point (assuming it's not using `e` format).

**Comment by jclark** [comment]
I have separated out the last part into a new issue #1065.
