### ISSUE TITLE
Improve type narrowing in the match statement

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-spec#827]
**Description:**
The [spec](https://ballerina.io/ballerina-spec/spec.html#match_statement) currently says

> A variable is the matched variable of a match-stmt if the action-or-expression following match is a variable-reference that references this variable. The type of a matched variable is subject to narrowing within regions of the match-stmt as follows. The matched variable has a narrowed type at the start of each match-clause, which is determined by previous match-clauses; the type for the first match-clause is the normal static type of the variable. Narrowing is applied to each match-clause as follows:
> 
> - let T be the narrowed type of the matched variable at the start of the match-clause;
> - let P be the union of the corresponding types of each match-pattern in the match-pattern-list of the match-clause;
> - let N be the intersection of T and P;
> - let R be the set difference of T and P;
> - if N is a subtype of readonly, then the narrowed type for the match-guard, if any, and statement-block of the match-clause is N; otherwise it is T;
> - if there is a match-guard, then the type narrowing described in Conditional variable type narrowing is done in addition to the type narrowing described here;
> - if R is a subtype of readonly and there is no match-guard, then the narrowed type for the next match-clause is R; otherwise, it is T.

Please consider the following related to the last point.

**Case I**
Added a new example in https://github.com/ballerina-platform/ballerina-spec/issues/827#issuecomment-826297380 to reflect applicable type better, since type narrowing wouldn't apply to the second clause here anyway.

<del> 

```ballerina
type Person record { 
    string name; 
};

function func(Person|error v) returns string? {
    match v {
        // `T` here is `Person|error`.
        error() => { // `P` is `error`, `N` is `error` and `R` is `Person`.

        }
        // Narrowed type here is `Person|error` (`T`) and not `Person` (`R`) because `Person` is not 
        // a subtype of `readonly`?
        var val => {
            return v.name; // compilation error?
        }
    }
}
```

For the first clause, `N` is `error` and `R` is `Person`.

But for the second clause, IIUC, the type applicable is still `Person|error`, and not `Person` because `Person` (`R`) is not a subtype of `readonly`? But can't we allow this? Isn't it enough if `N` is a subtype of `readonly`?

</del>

**Case II**
```ballerina
type Foo record {|
    readonly int a;
    readonly float b;
    readonly decimal c?;
|};

type Bar record {|
    readonly string b;
|};

type Baz record {|
    readonly float b;
    readonly string c;
|};

function func(Foo|Bar|Baz fb) {
    match fb {
        // `T` here is `Foo|Bar|Baz`
        {a: var a} => { // `P` is record {| any|error a; any|error...; |}, 
                        // `N` is `Foo`, `R` is `Bar|Baz`
            
        }
        // `R` is a subtype of `readonly` but since there is a match-guard 
        // the type applicable is `Foo|Bar|Baz`?
        {b: var b, c: var c, ...var rest} if b is float => {
            string str = c; // incompatible types: expected 'string', found '(decimal|string)'
        }
    }
}
```

Here, for the first clause, `N` is `Foo` and `R` is `Bar|Baz`.

Although both `N` and `R` are subtypes of `readonly`, since there is a match guard, wouldn't the type applicable to the second clause be `Foo|Bar|Baz` according to the last point? Even though we will never get to that point if the value looks like `Foo`?

**Comment by MaryamZi** [comment]
**Case I**
```ballerina
type Foo record {|
    readonly int a;
    readonly float b;
    readonly decimal c?;
|};

type Bar record {|
    string b;
|};

type Baz record {|
    readonly float b;
    readonly string c;
|};

function func(Foo|Bar|Baz fb) { // Only `Foo` and `Baz` are subtypes of `readonly`.
    match fb {
        // `T` here is `Foo|Bar|Baz`
        {a: var a} => { // `P` is record {| any|error a; any|error...; |}, 
                        // `N` is `Foo`, `R` is `Bar|Baz`
            // Since `N` is a subtype of `readonly`, type is narrowed.
            float b = fb.b;
        }
        // `R` of the previous clause is `Bar|Baz`, which is not a subtype of `readonly`, 
        // therefore the type applicable is `Foo|Bar|Baz`? Can this not be `Bar|Baz`?
        {b: var b, c: var c, ...var rest} if b is float => {
            string str = c; // incompatible types: expected 'string', found '(decimal|string)'
            string str2 = fb.c; // narrowed type of `fb` here is not `Baz`, so mismatched types?
        }
    }
}
```

For the first clause, N is `Foo` and R is `Bar|Baz`.

But IIUC, for the second clause, the type applicable is still `Foo|Bar|Baz`, and not `Bar|Baz` because `Bar|Baz` (R) is not a subtype of readonly? But can't we allow this? Isn't it enough if `N` is a subtype of readonly?

**Comment by MaryamZi** [comment]
**Case I**
```ballerina
type Foo record {|
    readonly int a;
    readonly float b;
    readonly decimal c?;
|};

type Bar record {|
    string b;
|};

type Baz record {|
    readonly float b;
    readonly string c;
|};

function func(Foo|Bar|Baz fb) { // Only `Foo` and `Baz` are subtypes of `readonly`.
    match fb {
        // `T` here is `Foo|Bar|Baz`
        {a: var a} => { // `P` is record {| any|error a; any|error...; |}, 
                        // `N` is `Foo`, `R` is `Bar|Baz`
            // Since `N` is a subtype of `readonly`, type is narrowed.
            float b = fb.b;
        }
        // `R` of the previous clause is `Bar|Baz`, which is not a subtype of `readonly`, 
        // therefore the type applicable is `Foo|Bar|Baz`? Can this not be `Bar|Baz`?
        {b: var b, c: var c, ...var rest} if b is float => {
            string str = c; // incompatible types: expected 'string', found '(decimal|string)'
            string str2 = fb.c; // narrowed type of `fb` here is not `Baz`, so mismatched types?
        }
    }
}
```

For the first clause, N is `Foo` and R is `Bar|Baz`.

But IIUC, for the second clause, the type applicable is still `Foo|Bar|Baz`, and not `Bar|Baz` because `Bar|Baz` (R) is not a subtype of readonly? But can't we allow this? Isn't it enough if `N` is a subtype of readonly?

**Comment by jclark** [comment]
Am I correct to say that your point is that although the rules are sound (do not lead to type-safety violations), they could be improved (i.e. we could infer narrower types) in certain cases involving a mix both readonly and not readonly?

**Comment by jclark** [comment]
We can clearly do better in the last bullet, in the case when the match-guard is equivalent to a type test.

**Comment by jclark** [comment]
What do you suggest that the last bullet should say?

**Comment by MaryamZi** [comment]
Yes, I think there are some scenarios where we can narrow the type for more match clauses like in Case I, by updating how the applicable type is decided. 

IMO, this will not only have an impact on type narrowing (of the matched variable), but will also help decide the types of the individual patterns more accurately. For example, `string str = c;` with the second match clause in Case I.

Can't we say
> if N is a subtype of readonly, then the narrowed type for the next match-clause is R; otherwise, it is T.

For the applicable type, I think there are also some cases where we can use a narrowed type, even in non-readonly cases.

For example, can't the applicable type at the start of the second clause of the following match statement be `Marks`?

```ballerina
type Employee record {|
    string name;
    int id;
|};

type Marks record {|
    int math;
    int physics;
    int chemistry;
|};

function func(Employee|Marks rec) {
    match rec {
        var {name, ...rest} => { // (1)

        }
        var {...rest} => { // (2)
            map<int> mn = rest;
        }
    }
}
```

**Comment by jclark** [comment]
For each match-clause C, we can compute a type L that a value must *look like* when the statement-block of C is executed. L is computed as the set difference of a type P (for positive) and type N (for negative)
- P is the union of the types of the match patterns in the match-pattern-list of C
- N is the union of the types of the match patterns in match-pattern-list of every match-clause that precedes C and that does not have a match-guard

Let T be the type of the matched variable at the start of the match-statement.

The the narrowed type of the matched variable for the match-guard, if any, and the statement-block of C is the *read-only intersection* of T and L, where the read-only intersection operation  is defined analogously to the the [read-only difference operation](https://ballerina.io/spec/lang/2021R1/#conditional_variable_type_narrowing) used for conditional type narrowing as follows.

We use the notation T &<sub>ro</sub> S for the read-only difference of T and S. T &<sub>ro</sub> S is computed separately for each uniform type. Let T<sup>U</sup> be the subset of T belonging to uniform type U, i.e. the intersection of T and U. For a uniform type U that is immutable, T<sup>U</sup> &<sub>ro</sub> S<sup>U</sup> is the same as T<sup>U</sup> & S<sup>U</sup>; for a uniform type U that is mutable, T<sup>U</sup> &<sub>ro</sub> S<sup>U</sup> is empty if T<sup>U</sup> & S<sup>U</sup> is empty, and T<sup>U</sup> otherwise. T &<sub>ro</sub> S is the union for every uniform type U of T<sup>U</sup> &<sub>ro</sub> S<sup>U</sup>.

(The definition of -<sup>ro</sup> make T<sup>U</sup> -<sub>ro</sub> S<sup>U</sup> empty if T<sup>U</sup> is a subset of S<sup>U</sup>: an equivalent and perhaps less confusing formulation is to say it is empty if T<sup>U</sup> - S<sup>U</sup> is empty.)

This definition of read-only intersection ensures that if a value x belongs to T and looks like S, then x belongs to T &<sub>ro</sub> S.

Type narrowing from the type-guards is done on top of this.

**Comment by jclark** [comment]
@MaryamZi I would like to deal with your example in https://github.com/ballerina-platform/ballerina-spec/issues/827#issuecomment-828204811 separately, since I believe it is not specific to match statements. What I propose in https://github.com/ballerina-platform/ballerina-spec/issues/827#issuecomment-895601520 is at the same level as what the spec does for conditional type narrowing, but there is scope for improvement in both.
