### ISSUE TITLE
Should the xml:strip function modify XML sequence

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-spec#834]
**Description:**
Though spec doesn't specifically say so (xml proposal says `Membership of sequences not mutable`), we don't change the membership of a sequence. But if we are to call `xml:strip` on a sequence, it seems we do need to modify the sequence as the strip function seems to be a mutating function.

**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**

**Comment by jclark** [comment]
XML sequences can't be mutated and don't have storage identity: you can't modify an XML sequence anymore than you can modify  an integer. "Removing comments" does not imply mutation for XML, any more than "subtracting 17" would imply mutation for integers.

The prose needs rewriting though, because it was written before text items were chunked.

**Comment by rdhananjaya** [comment]
One more question, does this means `strip` is a non-destructive function (as in we should create a new value skipping unwanted items) or we mutate the original value using `setChildren` and so on.

**Comment by jclark** [comment]
strip does not look inside elements: it just looks at the constituents of the sequence.

**Comment by jclark** [comment]
I rewrote the doc comment. Hopefully it's clear now.

**Comment by jclark** [comment]
setChildren mutates an element not a sequence.

**Comment by rdhananjaya** [comment]
Thank you, current implementation of strip does not look at elements but we thought it was a deviation from the doc comment and try to fix it. May be we don't have to change the current behavior.
