### ISSUE TITLE
Introduce a new `bal` command to generate cloud artifacts and remove `--cloud` option from `bal build`

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-spec#967]
In Swan Lake Beta3 and all previous releases, the `--cloud` option in `bal build` is used to generated artifacts for cloud providers such as Kubernetes, Docker, and Choreo. https://github.com/ballerina-platform/ballerina-spec/blob/master/c2c/code-to-cloud-spec.md#building-cloud-artifacts

For Swan Lake Beta4, we decided to make this functionality more first-class with top-level `bal` command. 

We are yet to finalize the command name. Here are some suggestions:
- `bal cloud`
- `bal c2c`

**Comment by sanjiva** [comment]
If I've done `bal build` already and then do `bal cloud` won't it (often/sometimes) mean rebuilding as well since there may be code changes?

If so we need to indicate that there are 2 build approaches: regular build and cloud build. In that case I prefer `bal build cloud` instead of `bal cloud` as that will be more confusing.

**Comment by xlight05** [comment]
Just a thought, I feel like when we make `bal cloud` a separate command, we hide the fact that this command is executed in the build time from the user (as we support artifact generation in buildtime).
